blueprint:
  name: Motion activated lights
  description: Turn on a light when motion is detected
  domain: automation
  source_url: https://github.com/nielsrowinbik/home/blob/master/blueprints/nielsrowinbik/motion_light.yaml
  input:
    motion_sensor:
      name: Motion sensor
      selector:
        entity:
          device_class: motion
          domain: binary_sensor
    light_target:
      name: Light(s)
      description: Select the light(s) to set
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_sensor
  from: "off"
  to: "on"

action:
  - service: light.turn_on
    target: !input light_target
    data:
      brightness_pct: "{{ state('sensor.circadian_values')|float }}"
      kelvin: "{{ state_attr('sensor.circadian_values', 'colortemp')|float }}"
  - wait_for_trigger:
      platform: state
      entity_id: !input motion_sensor
      from: "on"
      to: "off"
  - delay: !input no_motion_wait
  - service: light.turn_off
    target: !input light_target
