automation:
  - alias: Toggle Hallway spots through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/hallway_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click in ['single', 'double'] }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.hallway_spots

  - alias: Toggle Hallway spots through motion sensor
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion
        to: "off"
      - platform: state
        entity_id: binary_sensor.hallway_motion
        to: "on"
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.to_state.state == 'off' }}"
        - condition: template
          value_template: "{{ states('sensor.hallway_illuminance') < states('input_number.hallway_illuminance_threshold') }}"
    action:
      - service_template: "light.turn_{{ trigger.to_state.state }}"
        data:
          entity_id: light.hallway_spots

  - alias: Turn on Hallway spots when door opens
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    action:
      - service: light.turn_on
        data:
          entity_id: light.hallway_spots

input_number:
  hallway_illuminance_threshold:
    icon: mdi:tune
    max: 100
    min: 0
    mode: box
    name: Hallway illuminance threshold
    step: 1


light:
  - platform: mqtt
    brightness: true
    command_topic: "zigbee2mqtt/hallway_spots/set"
    name: Hallway spots
    schema: json
    state_topic: "zigbee2mqtt/hallway_spots"