automation:
  - alias: Turn working mode on
    trigger:
      - entity_id: input_boolean.working
        platform: state
        to: "on"
    action:
      - service: scene.apply
        data:
          entities:
            # light.office_desk: on
            light.office_worktop: on

  - alias: Turn working mode off
    trigger:
      - entity_id: input_boolean.working
        platform: state
        to: "off"
    action:
      - service: scene.apply
        data:
          entities:
            # light.office_desk: off
            light.office_worktop: off

input_boolean:
  working:
    name: Working
    initial: false