automation:
  - alias: Toggle Toilet spot through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/toilet_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click in ['single', 'double'] }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.toilet_spot

  - alias: Toggle Toilet spot through motion sensor
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_motion
        to: "off"
      - platform: state
        entity_id: binary_sensor.toilet_motion
        to: "on"
    action:
      - service_template: "light.turn_{{ trigger.to_state.state }}"
        data:
          entity_id: light.toilet_spot

  - alias: Turn on Toilet spot when door opens
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_door
        to: "on"
    action:
      - service: light.turn_on
        data:
          entity_id: light.toilet_spot

  - alias: Fix toilet spot brightness as it turns on
    trigger:
      - platform: state
        entity_id: light.toilet_spot
        to: "on"
    condition:
      - condition: template
        value_template: "{{ not is_state_attr('light.toilet_spot', 'brightness', 1 if is_state('input_select.scene', 'Night') else 255) }}"
    action:
      - service: script.fix_toilet_spot_brightness

script:
  fix_toilet_spot_brightness:
    alias: Fix toilet spot brightness
    sequence:
      - condition: template
        value_template: "{{ not is_state_attr('light.toilet_spot', 'brightness', 1 if is_state('input_select.scene', 'Night') else 255) }}"
      - service: light.turn_on
        data_template:
          entity_id: light.toilet_spot
          brightness: "{{ 1 if is_state('input_select.scene', 'Night') else 255 }}"