automation:
  - alias: Toggle Toilet spot through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/toilet_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click in ['single', 'double'] }}"
    action:
      - service: light.toggle
        data_template:
          brightness: "{{ 1 if is_state('sensor.current_scene', 'Night') else 255 }}"
          entity_id: light.toilet_spot
          transition: 0.5

  - alias: Turn on Toilet spot when door opens or through motion
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_door
        to: "on"
      - platform: state
        entity_id: binary_sensor.toilet_motion
        to: "on"
    action:
      - service: light.turn_on
        data_template:
          brightness: "{{ 1 if is_state('sensor.current_scene', 'Night') else 255 }}"
          entity_id: light.toilet_spot
          transition: 0.5

  - alias: Turn off Toilet spot
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_motion
        to: "off"
    action:
      - service: light.turn_off
        data:
          entity_id: light.toilet_spot
          transition: 0.5