automation:
  - alias: Notify to suggest bedtime
    description: Sends a notification when we think the user will want to go to bed
    trigger:
      - platform: state
        entity_id: binary_sensor.suggest_bedtime
        to: "on"
    action:
      # TODO: Add an action (or tap action) that turns on night mode
      # TODO: Give this notification some sort of identifyer so we don't send it multiple times
      # TODO: Use the identifier to dismiss the notification when it's no longer relevant
      - service: notify.all_devices
        data:
          title: "{{ state_attr('binary_sensor.suggest_bedtime', 'title') }}"
          message: "{{ state_attr('binary_sensor.suggest_bedtime', 'message') }}"
          data:
            channel: Insights

binary_sensor:
  - platform: template
    sensors:
      suggest_bedtime:
        attribute_templates:
          title: Ready to go to bed?
          message: Tap to settle down
        friendly_name: Suggest bedtime
        value_template: "{{ is_state('input_boolean.night_mode', 'off') and is_state('binary_sensor.bedtime', 'on') }}"
  - platform: tod
    name: Bedtime
    after: "21:50"
    before: "06:30"
