automation:
  - alias: Notify to suggesting movie mode
    description: Sends a notification when we think the user will want to dim the lights to watch a movie
    trigger:
      - platform: state
        entity_id: binary_sensor.suggest_movie
        to:
          - "off"
          - "on"
    action:
      # TODO: Add an action (or tap action) that turns on movie mode
      - service: notify.all_devices
        data:
          title: "{{ state_attr('binary_sensor.suggest_movie', 'title') }}"
          message: "{{ state_attr('binary_sensor.suggest_movie', 'message') if trigger.to_state.state == 'on' else 'clear_notification' }}"
          data:
            channel: Insights
            tag: suggest_movie

binary_sensor:
  - platform: template
    sensors:
      suggest_movie:
        attribute_templates:
          title: Watching a movie?
          message: Tap to dim the lights
        friendly_name: Suggest movie
        # TODO: Improve detecting TV state. We should probably take the current app into account as well
        value_template: "{{ is_state('input_boolean.movie_mode', 'off') and is_state('media_player.living_room_android_tv', 'idle') }}"
