automation:
  - alias: Notify to suggest bedtime
    description: Sends a notification when we think the user will want to go to bed
    trigger:
      - platform: state
        entity_id: binary_sensor.suggest_bedtime
        to:
          - "off"
          - "on"
    action:
      # TODO: Add an action (or tap action) that turns on night mode
      - service: notify.all_devices
        data:
          title: "{{ state_attr('binary_sensor.suggest_bedtime', 'title') }}"
          message: "{{ state_attr('binary_sensor.suggest_bedtime', 'message') if trigger.to_state.state == 'on' else 'clear_notification' }}"
          data:
            channel: Insights
            tag: suggest_bedtime

binary_sensor:
  - platform: template
    sensors:
      suggest_bedtime:
        attribute_templates:
          title: Ready to go to bed?
          message: Tap to settle down
        friendly_name: Suggest bedtime
        value_template: "{{ is_state('input_boolean.night_mode', 'off') and is_state('binary_sensor.bedtime', 'on') }}"
  - platform: tod
    name: Bedtime
    after: "21:50"
    before: "06:30"
