default_config:

homeassistant:
  name: Niels and Laura's Home
  latitude: !secret location_lat
  longitude: !secret location_long
  unit_system: metric
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages/
