homeassistant:
  name: Niels and Laura's Home
  latitude: !secret location_lat
  longitude: !secret location_long
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages/
  customize: !include customize.yaml

browser_mod:

cloud:
  google_actions:
    filter:
      exclude_entities:
        # - light.hallway_spot_1
        # - light.hallway_spot_2
        - light.kitchen_spot_1
        - light.kitchen_spot_2
        - light.living_room_spot_1
        - light.living_room_spot_2
        - light.living_room_spot_3
        - light.living_room_spot_4
        - light.living_room_spot_5
      include_domains:
        - climate
        - light
        - scene
        - script

cloudflare:
  email: !secret cloudflare_email
  api_key: !secret cloudflare_api_key
  zone: !secret cloudflare_zone
  records:
    - home

config:

discovery:

emulated_roku:
  servers:
    - name: Home Assistant
      listen_port: 8060

frontend:
  themes: !include_dir_named themes/

http:
  base_url: !secret base_url

lovelace:
  dashboards:
    ui-home:
      filename: ui-home.yaml
      icon: mdi:home-variant-outline
      mode: yaml
      show_in_sidebar: true
      title: Home
    ui-settings:
      filename: ui-settings.yaml
      icon: mdi:settings-outline
      mode: yaml
      require_admin: true
      show_in_sidebar: true
      title: Settings
  mode: yaml
  resources:
    - url: https://fonts.googleapis.com/css?family=Product+Sans:300,400,500
      type: css
    - url: /local/js/card-mod.js?v=v11.0.0
      type: module
    - url: /local/js/custom-header.js?v=v1.3.2
      type: module
    - url: /local/js/google-home-assistant.js?v=v0.8.0
      type: module
    - url: /local/js/simple-weather-card.js?v=0.7.2
      type: module
    - url: /local/js/homekit-panel-card.js?v=1.1.7
      type: module

mobile_app:

person:

ssdp:

sun:

zeroconf: