homeassistant:
  name: Niels and Laura's Home
  latitude: !secret location_lat
  longitude: !secret location_long
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages/
  customize: !include customize.yaml

cloud:
  google_actions:
    filter:
      include_domains:
        - light
        - scene
      include_entities:
        - script.scene_sync

config:

discovery:

emulated_roku:
  servers:
    - name: Home Assistant
      listen_port: 8060

frontend:

history:
  exclude:
    entities:
      - group.everyone

http:
  base_url: !secret base_url

lovelace:
  mode: yaml

person:

recorder:
  # db_url: mysql://<USER>:<PAsS>@<NAS_IP>:3307/<DB_NAME>?charset=utf8
  db_url: !secret db_url
  exclude:
    entities:
      - binary_sensor.remote_ui
  include:
    domains:
      - binary_sensor
      - climate
      - light
    entities:
      - group.everyone
      - input_select.presence
      - input_select.primary_scene
      - input_select.secondary_scene
      - person.laura
      - person.niels
      - sensor.living_room_heating
      - sensor.living_room_humidity
      - sensor.living_room_temperature
      - sensor.time_of_day
  purge_keep_days: 7

sun:

system_health:

tado:
  username: !secret tado_username
  password: !secret tado_password

updater:
