homeassistant:
  name: Niels and Laura's Home
  latitude: !secret location_lat
  longitude: !secret location_long
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages/
  customize: !include customize.yaml

automation: !include_dir_merge_list automation/

circadian_lighting:
  max_colortemp: 4000
  min_colortemp: 2200
  transition: 60

cloud:
  google_actions:
    filter:
      include_domains:
        - light
        - scene

config:

discovery:

emulated_roku:
  host_ip: !secret hass_ip

frontend:
  themes: !include_dir_named themes/

history:
  exclude:
    domains:
      - binary_sensor
      - sun
    entities:
      - group.everyone

http:
  base_url: !secret base_url

logbook:
  exclude:
    domains:
      - binary_sensor
      - climate
    entities:
      - group.everyone

lovelace:
  mode: yaml

recorder:
  db_url: !secret db_url
  exclude:
    entities:
      - sensor.circadian_values
      - sensor.living_room_tado_mode
      - sensor.niels_lauras_home_tado_bridge_status
      - sensor.upcoming_alarm
      - switch.circadian_lighting_circadian_lighting
      - switch.harmony_activity_listen_music
      - switch.harmony_activity_play_game
      - switch.harmony_activity_watch_cc
      - switch.harmony_activity_watch_tv
  include:
    domains:
      - binary_sensor
      - climate
      - sensor
      - sun
      - switch
    entities:
      - input_select.presence
      - input_select.primary_scene
      - input_select.secondary_scene
      - group.everyone
      - group.laura
      - group.niels
  purge_keep_days: 7

sun:

tado:
  username: !secret tado_username
  password: !secret tado_password

tts:
  - platform: google

updater: