homeassistant:
  name: Niels and Laura's Home
  latitude: !secret location_lat
  longitude: !secret location_long
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages/
  customize: !include customize.yaml

automation: !include_dir_merge_list automation/

cloud:
  google_actions:
    filter:
      include_domains:
        - light
        - scene
      include_entities:
        - script.scene_sync

config:

discovery:

emulated_roku:
  servers:
    - name: Home Assistant
      listen_port: 8060

frontend:
  themes: !include_dir_named themes/

history:
  exclude:
    entities:
      - group.everyone

http:
  base_url: !secret base_url

logbook:
  exclude:
    domains:
      - binary_sensor
      - climate
    entities:
      - group.everyone
  include:
    entities:
      - automation.synchronise_scene_to_time_of_day

lovelace:
  mode: yaml

panel_iframe:
  zigbee2mqtt_networkmap:
    title: Zigbee Map
    url: /local/zigbee2mqtt_networkmap/map.html?engine=dot
    icon: mdi:lan

recorder:
  db_url: !secret db_url
  include:
    domains:
      - binary_sensor
      - climate
      - light
    entities:
      - group.everyone
      - group.laura
      - group.niels
      - input_select.presence
      - input_select.primary_scene
      - input_select.secondary_scene
      - sensor.living_room_heating
      - sensor.living_room_humidity
      - sensor.living_room_temperature
      - sensor.time_of_day
  purge_keep_days: 7

sun:

system_health:

tado:
  username: !secret tado_username
  password: !secret tado_password

updater:

zigbee2mqtt_networkmap:
