homeassistant:
  name: Niels and Laura's Home
  latitude: !secret location_lat
  longitude: !secret location_long
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages/
  customize: !include customize.yaml

cloud:
  google_actions:
    filter:
      exclude_entities:
        - light.kitchen_spot_1
        - light.kitchen_spot_2
      include_domains:
        - light
        - scene
        - script

config:

discovery:
  ignore:
    - plex_mediaserver

emulated_roku:
  servers:
    - name: Home Assistant
      listen_port: 8060

frontend:
  themes: !include_dir_named themes/

http:
  base_url: !secret base_url

lovelace:
  mode: yaml

person:

sun:

system_health:

tado:
  username: !secret tado_username
  password: !secret tado_password

updater:
