homeassistant:
  name: Niels and Laura's Home
  latitude: !secret location_lat
  longitude: !secret location_long
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages/
  customize: !include customize.yaml

cloud:
  google_actions:
    filter:
      exclude_entities:
        # - light.hallway_spot_1
        # - light.hallway_spot_2
        - light.kitchen_spot_1
        - light.kitchen_spot_2
        - light.living_room_spot_1
        - light.living_room_spot_2
        - light.living_room_spot_3
        - light.living_room_spot_4
        - light.living_room_spot_5
      include_domains:
        - light
        - scene
        - script

cloudflare:
  email: !secret cloudflare_email
  api_key: !secret cloudflare_api_key
  zone: !secret cloudflare_zone
  records:
    - home

config:

discovery:
  ignore:
    - plex_mediaserver

emulated_roku:
  servers:
    - name: Home Assistant
      listen_port: 8060

frontend:
  themes: !include_dir_named themes/

http:
  base_url: !secret base_url

lovelace:
  mode: yaml

mobile_app:

person:

sun:

zeroconf: