custom_header:
  header_css: "box-shadow: none !important;"
  split_mode: true
resources:
  - url: https://fonts.googleapis.com/css?family=Product+Sans:300,400,500
    type: css
  - url: /local/js/lottie.min.js?v=5.6.0
    type: js
  - url: /local/js/card-mod.js?v=11
    type: module
  - url: /local/js/custom-header.js?v1.3.2
    type: module
  - url: /local/js/google-home-assistant.js?v0.7.0
    type: module
#   - url: "http://127.0.0.1:5000/google-home-assistant.js"
#     type: module
title: " "
views:
  - title: Home
    path: home
    icon: mdi:home-variant-outline
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:google-home-menu
            title: Niels & Laura's Home
            cards:
              - type: custom:google-home-menu-item
                entity: group.all_lights
                color: yellow
              - type: custom:google-home-menu-item
                entity: group.all_media_players
                color: green
              - type: custom:google-home-menu-item
                entity: group.all_scenes
                color: blue
              - type: custom:google-home-menu-item
                entity: group.everyone
                color: cyan
              - type: custom:google-home-menu-item
                entity: climate.living_room
                color: red
                icon: mdi:thermometer
                name: Thermostat
              - type: custom:google-home-menu-item
                entity: sensor.google_wifi_status
                color: dark-green
                icon: mdi:wifi
                name: Wi-Fi
              - type: custom:google-home-menu-item
                entity: group.all_scripts
                color: purple
              - type: custom:google-home-menu-item
                entity: group.all_scripts
                color: none
                icon: mdi:settings-outline
                name: Settings
                tap_action:
                  action: navigate
                  navigation_path: /lovelace/settings
          - type: custom:google-home-grid
            title: Downstairs
            cards:
              - type: custom:google-home-grid-item
                entity: media_player.downstairs_speaker
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
                icon: /local/images/google_assistant_speaker.svg
          - type: custom:google-home-grid
            title: Kitchen
            cards:
              - type: custom:google-home-grid-item
                entity: group.kitchen_lights
                actions:
                  - label: "Off"
                    service: homeassistant.turn_off
                  - label: "On"
                    service: homeassistant.turn_on
                icon: /local/images/lightgroup.svg
              - type: custom:google-home-grid-item
                entity: media_player.kitchen_speakers
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
                icon: /local/images/speaker.svg
          - type: custom:google-home-grid
            title: Living Room
            cards:
              - type: custom:google-home-grid-item
                entity: light.living_room_pendant
                actions:
                  - label: "Off"
                    service: light.turn_off
                  - label: "On"
                    service: light.turn_on
                icon: /local/images/light.svg
              - type: custom:google-home-grid-item
                entity: light.living_room_spots
                actions:
                  - label: "Off"
                    service: light.turn_off
                  - label: "On"
                    service: light.turn_on
                icon: /local/images/light.svg
              - type: custom:google-home-grid-item
                entity: media_player.living_room_tv
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
                icon: /local/images/chromecast.svg
              - type: custom:google-home-grid-item
                entity: media_player.living_room_home_mini
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
                icon: /local/images/google_home_mini.svg
              - type: custom:google-home-grid-item
                entity: media_player.living_room_speakers
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
                icon: /local/images/speaker.svg
              - type: custom:google-home-grid-item
                entity: climate.living_room
                icon: /local/images/thermostat.svg
              - type: custom:google-home-grid-item
                entity: switch.remote_chromecast
                actions:
                  - label: Turn off
                    service: switch.turn_off
                    state: "on"
                icon: /local/images/remote.svg
              - type: custom:google-home-grid-item
                entity: switch.remote_receiver
                actions:
                  - label: Turn off
                    service: switch.turn_off
                    state: "on"
                icon: /local/images/remote.svg
              - type: custom:google-home-grid-item
                entity: switch.remote_tv
                actions:
                  - label: Turn off
                    service: switch.turn_off
                    state: "on"
                icon: /local/images/remote.svg
              - type: custom:google-home-grid-item
                entity: switch.remote_xbox
                actions:
                  - label: Turn off
                    service: switch.turn_off
                    state: "on"
                icon: /local/images/remote.svg
              - type: custom:google-home-grid-item
                entity: sensor.google_wifi_status
                icon: /local/images/generic_device.svg
                name: Google Wifi router
          - type: custom:google-home-grid
            title: Toilet
            cards:
              - type: custom:google-home-grid-item
                entity: light.toilet_spot
                actions:
                  - label: "Off"
                    service: light.turn_off
                  - label: "On"
                    service: light.turn_on
                icon: /local/images/light.svg
          - type: custom:google-home-grid
            title: Groups
            cards:
              - type: custom:google-home-grid-item
                entity: media_player.everywhere
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
                icon: /local/images/speaker.svg
                group_size: 3
              - type: custom:google-home-grid-item
                entity: media_player.upstairs
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
                icon: /local/images/speaker.svg
                group_size: 2
            counter_text: group
  - title: Settings
    path: settings
    icon: mdi:settings-outline
    panel: true
    cards:
      - type: vertical-stack
        cards: []
