resources:
  - url: /local/js/vertical-stack-in-card.js?v=0.1.1
    type: js
title: " "
views:
  - cards:
      - cards:
          - cards:
              - columns: 6
                entities:
                  - person.niels
                  - person.laura
                  - group.george
                  - input_select.scene
                  - input_select.activity
                show_name: false
                type: glance
            title: Niels & Laura's Home
            type: custom:vertical-stack-in-card
          - card:
              entities:
                - type: call-service
                  name: Would you like to active the Night scene?
                  action_name: Okay
                  icon: mdi:google-assistant
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.night
              type: entities
            conditions:
              - entity: input_select.scene
                state: Evening
            type: conditional
        type: vertical-stack
    path: home
    title: Home
  - cards:
      - cards:
          - entities:
              - entity: media_player.downstairs_speaker
                icon: mdi:speaker
            show_header_toggle: false
            title: Downstairs
            type: entities
          - entities:
              - entity: binary_sensor.backdoor_contact_sensor
                name: Backdoor
              - entity: media_player.kitchen_speakers
                icon: mdi:speaker
                name: Speakers
              - label: Lights
                type: section
              - entity: light.kitchen_spots
                name: Spots
              - entity: light.kitchen_mood_lighting
                name: Mood lighting
              - entity: light.kitchen_worktop
                name: Worktop light
            show_header_toggle: false
            title: Kitchen
            type: entities
          - entities:
              - entity: media_player.living_room_tv
                name: Chromecast
              - entity: media_player.living_room_speakers
                icon: mdi:speaker
                name: Speakers
              - entity: climate.living_room
                name: Thermostat
              - label: Lights
                type: section
              - entity: light.living_room_pendant
                name: Pendant light
            show_header_toggle: false
            title: Living Room
            type: entities
          - entities:
              - entity: binary_sensor.toilet_occupancy
                name: Occupancy
              - label: Lights
                type: section
              - entity: light.toilet_spot
                name: Spot
            show_header_toggle: false
            title: Toilet
            type: entities
        type: vertical-stack
    icon: mdi:monitor-dashboard
    path: dashboard
    title: Dashboard
  - cards:
      - cards:
          - entities:
              - script.scene_sync
              - automation.synchronise_scene_to_time_of_day
              - automation.turn_off_night_scene
              - label: Settings
                type: section
              - input_number.morning_threshold
              - input_number.day_threshold
              - input_number.afternoon_threshold
              - input_number.early_evening_threshold
              - input_number.evening_threshold
              - input_number.max_sun_elevation_decrease
            show_header_toggle: false
            title: Scenes
            type: entities
          - entities:
              - script.reset_volume
            show_header_toggle: false
            title: Media
            type: entities
          - entities:
              - entity: script.generate_network_map
                name: Generate network map
              - input_boolean.zigbee_permit_join
            show_header_toggle: false
            title: Zigbee
            type: entities
        type: vertical-stack
    icon: mdi:settings
    path: settings
    title: Settings
