title: " "
views:
  - cards:
      - cards:
          - entities:
              - input_select.presense
              - input_select.primary_scene
              - input_select.secondary_scene
            show_header_toggle: false
            title: Niels & Laura's Home
            type: entities
        type: vertical-stack
    path: home
    title: Home
