title: Home
views:
  - cards:
      - type: vertical-stack
        cards:
          - entities:
              - script.scene_sync
              - input_boolean.keep_kitchen_spots_on
              - script.turn_off_night_scene
              - input_boolean.zigbee_permit_join
            show_header_toggle: false
            type: entities
          - entities:
              - climate.living_room
            show_header_toggle: false
            type: entities
          - entities:
              - input_datetime.workday_alarm
              - input_datetime.off_day_alarm
            show_header_toggle: false
            type: entities
          - entities:
              - input_number.morning_threshold
              - input_number.day_threshold
              - input_number.afternoon_threshold
              - input_number.early_evening_threshold
              - input_number.evening_threshold
            show_header_toggle: false
            type: entities
    path: index