resources:
  - url: https://fonts.googleapis.com/css?family=Product+Sans:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i
    type: css
  - url: /local/custom-css/styles.css
    type: css
  - url: /local/custom-lovelace/card-tools.js?v=0.3.0
    type: js
  - url: /local/custom-lovelace/card-modder.js?v=0.1.0
    type: js
  - url: /local/custom-lovelace/mini-media-player-bundle.js?v=0.9.8
    type: module
  - url: /local/custom-lovelace/vertical-stack-in-card.js?v=0.1.1
    type: js
  - url: /local/custom-lovelace/group-card.js?v=1.0.0
    type: js
title: " "
views:
  - cards:
      - cards:
          - columns: 6
            entities:
              - group.niels
              - group.laura
              - group.george
              - input_select.primary_scene
              - input_select.secondary_scene
            show_name: false
            type: glance
        title: Niels & Laura's Home
        type: custom:vertical-stack-in-card
      - card:
          entities:
            - type: call-service
              name: Would you like to active the Night scene?
              action_name: Okay
              icon: mdi:google-assistant
              service: scene.turn_on
              service_data:
                entity_id: scene.night
          type: entities
        conditions:
          - entity: input_select.primary_scene
            state: Evening
        type: conditional
    path: home
    title: Home
  - cards:
      - cards:
          - entities:
              - input_select.presence
              - input_select.primary_scene
              - input_select.secondary_scene
            show_header_toggle: false
            title: Niels & Laura's Home
            type: entities
          - entities:
              - entity: binary_sensor.backdoor_contact_sensor
                name: Backdoor
              - label: Lights
                type: section
              - entity: light.kitchen_worktop
                name: Worktop light
              - entity: light.kitchen_mood_lighting
                name: Mood lighting
            show_header_toggle: false
            title: Kitchen
            type: entities
          - entities:
              - entity: climate.living_room
                name: Thermostat
              - label: Lights
                type: section
              - entity: light.living_room_pendant
                name: Pendant light
            show_header_toggle: false
            title: Living Room
            type: entities
        type: vertical-stack
    icon: mdi:monitor-dashboard
    path: dashboard
    title: Dashboard
  - cards:
      - entities:
          - script.scene_sync
          - sun.sun
          - sensor.sun_direction
          - sensor.time_of_day
          - label: Settings
            type: section
          - input_number.morning_threshold
          - input_number.day_threshold
          - input_number.afternoon_threshold
          - input_number.early_evening_threshold
          - input_number.evening_threshold
          - input_number.max_sun_elevation_decrease
          - label: Automations
            type: section
          - automation.synchronise_scene_to_time_of_day
          - automation.handle_scene_override
          - automation.reactivate_secondary_scene_upon_primary_scene_switch
          - automation.turn_off_night_scene
        show_header_toggle: false
        title: Scenes
        type: entities
      - entities:
          - input_boolean.zigbee_permit_join
          - timer.zigbee_permit_join
          - sensor.bridge_state
        show_header_toggle: false
        title: Zigbee
        type: entities
    icon: mdi:settings
    path: settings
    title: Settings
