title: " "
views:
  - cards:
      - type: vertical-stack
        cards:
          - content: >-
              # Good afternoon, {{ user.split(' ')[0] }}!
            type: markdown
          - backdrop: true
            entity: weather.home
            name: " "
            primary_info: false
            secondary_info: false
            type: custom:simple-weather-card
    path: home
    title: Overview
  - cards:
      - card:
          type: vertical-stack
        card_param: cards
        filter:
          include:
            - domain: media_player
              options:
                artwork: material
                hide:
                  progress: true
                  power: true
                  source: true
                  volume: true
                type: custom:mini-media-player
              or:
                - state: playing
                - state: paused
        sort:
          method: last_updated
        type: custom:auto-entities
    path: media
    title: Media
  - cards:
      - type: vertical-stack
        cards:
          - entities:
              - input_boolean.guest_mode
              - input_boolean.vacation_mode
              - input_datetime.workday_alarm
              - input_datetime.off_day_alarm
              - type: section
                label: Time of day
              - entity: sensor.sun_elevation
                name: Current sun elevation
              - entity: sensor.time_of_day
                name: Current time of day
              - base_config:
                  tap_action:
                    action: call-service
                    service: script.set_threshold
                buttons:
                  - name: Set Morning
                    tap_action:
                      service_data:
                        entity: input_number.morning_threshold
                  - name: Set Day
                    tap_action:
                      service_data:
                        entity: input_number.day_threshold
                  - name: Set Afternoon
                    tap_action:
                      service_data:
                        entity: input_number.afternoon_threshold
                  - name: Set Early evening
                    tap_action:
                      service_data:
                        entity: input_number.early_evening_threshold
                  - name: Set Evening
                    tap_action:
                      service_data:
                        entity: input_number.evening_threshold
                  - name: Set Night
                    tap_action:
                      service_data:
                        entity: input_number.night_threshold
                type: custom:paper-buttons-row
              - input_number.morning_threshold
              - input_number.day_threshold
              - input_number.afternoon_threshold
              - input_number.early_evening_threshold
              - input_number.evening_threshold
              - input_number.night_threshold
              - type: section
                label: Kitchen illuminance
              - icon: mdi:brightness-6
                entity: binary_sensor.kitchen_motion
                name: Current kitchen illuminance
                secondary: Lights will {{ 'not' if is_state('binary_sensor.kitchen_sufficiently_lit', 'on') else '' }} turn on when triggered
                state: "{{ states('sensor.kitchen_illuminance') }}"
                type: custom:template-entity-row
              - input_number.kitchen_illuminance_threshold
            show_header_toggle: false
            title: Settings
            type: entities
    path: settings
    title: Settings
