title: " "
views:
  - cards:
      - type: vertical-stack
        cards:
          - entities:
              - icon: mdi:home-variant-outline
                name: Home state
                secondary: >-
                  {% if is_state('input_boolean.guest_mode', 'on') %}
                    Guest mode is on. Current scene is {{ states('sensor.current_scene') }}
                  {% elif is_state('sensor.current_scene', 'Away') %}

                  {% else %}
                    Current scene is {{ states('sensor.current_scene') }}
                  {% endif %}
                state: "{{ 'Occupied' if is_state('group.everyone', 'home') or is_state('input_boolean.guest_mode', 'on') else 'Empty' }}"
                type: custom:template-entity-row
              - entity: script.set_next_alarm
                icon: mdi:alarm
                name: Next alarm
                state: >-
                  {% if state_attr('input_datetime.next_alarm', 'day') == now().day %}
                    {{ states('input_datetime.next_alarm') | as_timestamp | timestamp_custom('Today at %H:%M', true) }}
                  {% elif state_attr('input_datetime.next_alarm', 'day') == now().day + 1 %}
                    {{ states('input_datetime.next_alarm') | as_timestamp | timestamp_custom('Tomorrow at %H:%M', true) }}
                  {% else %}
                    {{ states('input_datetime.next_alarm') | as_timestamp | timestamp_custom('%A at %H:%M', true) }}
                  {% endif %}
                type: custom:template-entity-row
              - entity: climate.living_room
                icon: mdi:thermometer
                name: Upstairs temperature
                secondary: >-
                  {% if is_state('climate.living_room', 'off') %}
                    Heating is turned off
                  {% elif is_state_attr('climate.living_room', 'hvac_action', 'idle') %}
                    Will keep Living Room at around {{ state_attr('climate.living_room', 'temperature') }}째
                  {% else %}
                    Heating to {{ state_attr('climate.living_room', 'temperature') }}째
                  {% endif %}
                state: >-
                  {% set kitchen = state_attr('climate.kitchen', 'current_temperature') | float %}
                  {% set livingRoom = state_attr('climate.living_room', 'current_temperature') | float %}

                  {{ ([kitchen, livingRoom] | sum / 2) | round(1) }}째
                type: custom:template-entity-row
              - icon: >-
                  {% set kitchen = state_attr('climate.kitchen', 'current_humidity') | float %}
                  {% set livingRoom = state_attr('climate.living_room', 'current_humidity') | float %}

                  {% set average = ([kitchen, livingRoom] | sum / 2) | round(1) %}

                  mdi:water-percent{{ '' if average >= 60 and average <= 70 else '-alert'  }}
                name: Upstairs humidity
                secondary: >-
                  {% set kitchen = state_attr('climate.kitchen', 'current_humidity') | float %}
                  {% set livingRoom = state_attr('climate.living_room', 'current_humidity') | float %}

                  {% set average = ([kitchen, livingRoom] | sum / 2) | round(1) %}

                  {% if average < 60 %}
                    Consider humidifying
                  {% elif average > 70 %}
                    Consider dehumidyfing
                  {% else %}
                  {% endif %}
                state: >-
                  {% set kitchen = state_attr('climate.kitchen', 'current_humidity') | float %}
                  {% set livingRoom = state_attr('climate.living_room', 'current_humidity') | float %}

                  {{ ([kitchen, livingRoom] | sum / 2) | round(1) }}%
                type: custom:template-entity-row
              - icon: mdi:thermometer
                name: Downstairs temperature
                state: >-
                  {% set bedroom = state_attr('climate.bedroom', 'current_temperature') | float %}
                  {% set bathroom = state_attr('climate.bathroom', 'current_temperature') | float %}
                  {% set office = state_attr('climate.office', 'current_temperature') | float %}

                  {{ ([bedroom, bathroom, office] | sum / 3) | round(1) }}째
                type: custom:template-entity-row
              - icon: >-
                  {% set bedroom = state_attr('climate.bedroom', 'current_humidity') | float %}
                  {% set bathroom = state_attr('climate.bathroom', 'current_humidity') | float %}
                  {% set office = state_attr('climate.office', 'current_humidity') | float %}

                  {% set average = ([bedroom, bathroom, office] | sum / 3) | round(1) %}

                  mdi:water-percent{{ '' if average >= 60 and average <= 70 else '-alert'  }}
                name: Downstairs humidity
                secondary: >-
                  {% set bedroom = state_attr('climate.bedroom', 'current_humidity') | float %}
                  {% set bathroom = state_attr('climate.bathroom', 'current_humidity') | float %}
                  {% set office = state_attr('climate.office', 'current_humidity') | float %}

                  {% set average = ([bedroom, bathroom, office] | sum / 3) | round(1) %}

                  {% if average < 60 %}
                    Consider humidifying
                  {% elif average > 70 %}
                    Consider dehumidyfing
                  {% else %}
                  {% endif %}
                state: >-
                  {% set bedroom = state_attr('climate.bedroom', 'current_humidity') | float %}
                  {% set bathroom = state_attr('climate.bathroom', 'current_humidity') | float %}
                  {% set office = state_attr('climate.office', 'current_humidity') | float %}

                  {{ ([bedroom, bathroom, office] | sum / 3) | round(1) }}%
                type: custom:template-entity-row
            type: entities
            show_header_toggle: false
            title: At a Glance
          - entities:
              - conditions:
                  - entity: sensor.current_scene
                    state_not: Away
                row:
                  entity: input_boolean.kitchen_bright_mode
                type: conditional
              - conditions:
                  - entity: sensor.current_scene
                    state_not: Away
                row:
                  entity: input_boolean.living_room_bright_mode
                type: conditional
              - conditions:
                  - entity: sensor.current_scene
                    state_not: Away
                  - entity: sensor.current_scene
                    state_not: Morning
                  - entity: sensor.current_scene
                    state_not: Night
                row:
                  entity: input_boolean.cooking_mode
                type: conditional
              - conditions:
                  - entity: sensor.current_scene
                    state_not: Away
                  - entity: sensor.current_scene
                    state_not: Morning
                  - entity: sensor.current_scene
                    state_not: Day
                  - entity: sensor.current_scene
                    state_not: Night
                row:
                  entity: input_boolean.movie_mode
                type: conditional
              - conditions:
                  - entity: sensor.current_scene
                    state_not: Away
                  - entity: sensor.current_scene
                    state_not: Morning
                  - entity: sensor.current_scene
                    state_not: Day
                row:
                  entity: input_boolean.night_mode
                type: conditional
              - conditions:
                  - entity: sensor.current_scene
                    state_not: Away
                row:
                  entity: input_boolean.work_mode
                type: conditional
            show_header_toggle: false
            title: Quick access
            type: entities
    icon: mdi:home-variant-outline
    path: home
    title: Home
  - cards:
      - type: vertical-stack
        cards:
          - entities:
              - input_boolean.guest_mode
              - input_boolean.vacation_mode
              - input_datetime.workday_alarm
              - input_datetime.off_day_alarm
              - type: section
                label: Time of day
              - entity: sensor.sun_elevation
                name: Current sun elevation
              - entity: sensor.time_of_day
                name: Current time of day
              - input_number.morning_threshold
              - input_number.day_threshold
              - input_number.afternoon_threshold
              - input_number.early_evening_threshold
              - input_number.evening_threshold
              - input_number.night_threshold
              - type: section
                label: Illuminance
              - input_number.hallway_illuminance_threshold
              - input_number.kitchen_illuminance_threshold
            show_header_toggle: false
            title: Settings
            type: entities
    icon: mdi:cog-outline
    path: settings
    title: Settings
