cch:
  hide_tabs: "0,1"
resources:
  - url: https://fonts.googleapis.com/css?family=Product+Sans:300,400,500
    type: css
  - url: /local/js/card-mod.js?v=11
    type: module
  - url: /local/js/compact-custom-header.js?v=1.4.9
    type: module
  - url: /local/js/google-home-assistant.js?v0.4.0
    type: module
title: " "
views:
  - title: Home
    path: home
    icon: mdi:home-variant-outline
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:google-home-menu
            title: Niels & Laura's Home
            cards:
              - type: custom:google-home-menu-item
                entity: input_select.activity
                color: indigo
                icon: mdi:pulse
                name: Activities
              - type: custom:google-home-menu-item
                entity: group.all_lights
                color: yellow
                icon: mdi:lightbulb-outline
                name: Lights
              - type: custom:google-home-menu-item
                entity: group.all_media_players
                color: green
                icon: mdi:music-note-outline
                name: Play
              - type: custom:google-home-menu-item
                entity: group.everyone
                color: cyan
                icon: mdi:account-group-outline
                name: People
              - type: custom:google-home-menu-item
                entity: input_select.scene
                color: blue
                icon: mdi:theme-light-dark
                name: Scenes
              - type: custom:google-home-menu-item
                entity: climate.living_room
                color: red
                icon: mdi:thermometer
                name: Thermostat
              - type: custom:google-home-menu-item
                entity: group.all_scripts
                color: purple
                icon: mdi:brightness-6
                name: Routines
              - type: custom:google-home-menu-item
                entity: group.all_scripts
                color: none
                icon: mdi:settings-outline
                name: Settings
                tap_action:
                  action: navigate
                  navigation_path: /lovelace/settings
          - type: custom:google-home-grid
            title: Downstairs
            cards:
              - type: custom:google-home-grid-item
                entity: media_player.downstairs_speaker
                icon: /local/icons/speaker.svg
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
          - type: custom:google-home-grid
            title: Kitchen
            cards:
              - type: custom:google-home-grid-item
                entity: group.kitchen_lights
                icon: /local/icons/lightgroup.svg
                name: Kitchen lights
                actions:
                  - label: "Off"
                    service: group.turn_off
                  - label: "On"
                    service: group.turn_on
              - type: custom:google-home-grid-item
                entity: media_player.kitchen_speakers
                icon: /local/icons/speaker.svg
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
          - type: custom:google-home-grid
            title: Living Room
            cards:
              - type: custom:google-home-grid-item
                entity: light.living_room_pendant
                icon: /local/icons/light.svg
                actions:
                  - label: "Off"
                    service: light.turn_off
                  - label: "On"
                    service: light.turn_on
              - type: custom:google-home-grid-item
                entity: media_player.living_room_tv
                icon: /local/icons/chromecast.svg
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
              - type: custom:google-home-grid-item
                entity: media_player.living_room_home_mini
                icon: /local/icons/google_home_mini.svg
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
              - type: custom:google-home-grid-item
                entity: media_player.living_room_speakers
                icon: /local/icons/speaker.svg
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
              - type: custom:google-home-grid-item
                entity: climate.living_room
                icon: /local/icons/thermostat.svg
          - type: custom:google-home-grid
            title: Toilet
            cards:
              - type: custom:google-home-grid-item
                entity: light.toilet_spot
                icon: /local/icons/light.svg
                actions:
                  - label: "Off"
                    service: light.turn_off
                  - label: "On"
                    service: light.turn_on
          - type: custom:google-home-grid
            title: Groups
            cards:
              - type: custom:google-home-grid-item
                entity: media_player.everywhere
                icon: /local/icons/speaker.svg
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
              - type: custom:google-home-grid-item
                entity: media_player.upstairs
                icon: /local/icons/speaker.svg
                actions:
                  - label: Play
                    service: media_player.media_play
                    state: paused
                  - label: Pause
                    service: media_player.media_pause
                    state: playing
  - title: Settings
    path: settings
    icon: mdi:settings-outline
    panel: true
    cards:
      - type: vertical-stack
        cards: []
