custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        active_tab_css: "color: var(--primary-color) !important;"
        all_tabs_css: "width: calc(50vw - 7px) !important; padding: 0px !important;"
        chevrons: false
        tab_conatiner_css: "margin: 0 !important; box-shadow: var(--ha-card-box-shadow) !important"
        tab_indicator_color: transparent
        split_mode: true
        shadow: false
title: " "
views:
  - cards:
      - type: vertical-stack
        cards:
          - entities:
              - icon: mdi:home-variant-outline
                name: Home state
                secondary: >-
                  {% if is_state('input_boolean.guest_mode', 'on') %}
                    Guest mode is on. Current scene is {{ states('sensor.current_scene') }}
                  {% elif is_state('sensor.current_scene', 'Away') %}

                  {% else %}
                    Current scene is {{ states('sensor.current_scene') }}
                  {% endif %}
                state: "{{ 'Occupied' if is_state('group.everyone', 'home') or is_state('input_boolean.guest_mode', 'on') else 'Empty' }}"
                type: custom:template-entity-row
              - active: "{{ is_state_attr('climate.living_room', 'hvac_action', 'heat') }}"
                icon: mdi:thermometer
                name: Upstairs temperature
                secondary: >-
                  {% if is_state('climate.living_room', 'off') %}
                    Heating is turned off
                  {% elif is_state_attr('climate.living_room', 'hvac_action', 'idle') %}
                    Will heat if temperature drops below {{ state_attr('climate.living_room', 'temperature') }}°
                  {% else %}
                    Heating to {{ state_attr('climate.living_room', 'current_temperature') }}°
                  {% endif %}
                state: "{{ state_attr('climate.living_room', 'current_temperature') }}°"
                type: custom:template-entity-row
              - icon: mdi:alarm
                name: Next alarm
                # secondary: >-
                #   {% if state_attr('input_datetime.next_alarm', 'day') == now().day %}
                #     Today is {{ 'a workday' if is_state('binary_sensor.today_is_a_workday', 'on') else 'an off day' }}
                #   {% else %}
                #     Tomorrow is {{ 'a workday' if is_state('binary_sensor.tomorrow_is_a_workday', 'on') else 'an off day' }}
                #   {% endif %}
                state: >-
                  {% if state_attr('input_datetime.next_alarm', 'day') == now().day %}
                    {{ states('input_datetime.next_alarm') | as_timestamp | timestamp_custom('Today at %H:%M', true) }}
                  {% elif state_attr('input_datetime.next_alarm', 'day') == now().day + 1 %}
                    {{ states('input_datetime.next_alarm') | as_timestamp | timestamp_custom('Tomorrow at %H:%M', true) }}
                  {% else %}
                    {{ states('input_datetime.next_alarm') | as_timestamp | timestamp_custom('%A at %H:%M', true) }}
                  {% endif %}
                type: custom:template-entity-row
            type: entities
            show_header_toggle: false
            title: At a Glance
          - entities:
              - entity: input_boolean.kitchen_bright_mode
              - conditions:
                  - entity: sensor.current_scene
                    state_not: Day
                row:
                  entity: input_boolean.living_room_bright_mode
                type: conditional
              - conditions:
                  - entity: sensor.current_scene
                    state_not: Morning
                  - entity: sensor.current_scene
                    state_not: Night
                row:
                  entity: input_boolean.cooking_mode
                type: conditional
              - conditions:
                  - entity: sensor.current_scene
                    state_not: Morning
                  - entity: sensor.current_scene
                    state_not: Day
                row:
                  entity: input_boolean.night_mode
                type: conditional
              - conditions:
                  - entity: binary_sensor.today_is_a_workday
                    state: "on"
                  - entity: sensor.current_scene
                    state_not: Night
                row:
                  entity: input_boolean.work_mode
                type: conditional
            show_header_toggle: false
            title: Quick access
            type: entities
          - card:
              title: Lights
              type: entities
            filter:
              exclude:
                - entity_id: "/[\\s\\S]*\\d$/"
              include:
                - domain: light
                  state: "on"
            show_empty: false
            type: custom:auto-entities
    icon: mdi:home-variant-outline
    path: home
    title: Home
  - cards:
      - type: vertical-stack
        cards:
          - entities:
              - input_boolean.guest_mode
              - input_boolean.vacation_mode
              - input_datetime.workday_alarm
              - input_datetime.off_day_alarm
              - type: section
                label: Time of day
              - input_number.morning_threshold
              - input_number.day_threshold
              - input_number.afternoon_threshold
              - input_number.early_evening_threshold
              - input_number.evening_threshold
              - input_number.night_threshold
              - type: section
                label: Illuminance
              - input_number.hallway_illuminance_threshold
              - input_number.kitchen_illuminance_threshold
              - type: section
                label: Zigbee
              - input_boolean.zigbee_permit_join
            show_header_toggle: false
            title: Settings
            type: entities
    icon: mdi:cog-outline
    path: settings
    title: Settings
