resources:
  - url: /local/custom-lovelace/card-tools.js?v=0.3.0
    type: js
  - url: /local/custom-lovelace/card-modder.js?v=0.1.0
    type: js
  - url: /local/custom-lovelace/mini-media-player-bundle.js?v=0.9.8
    type: module
title: " "
views:
  - cards:
      - cards:
          - card:
              entities:
                - input_select.presence
                - input_select.primary_scene
                - input_select.secondary_scene
              show_header_toggle: false
              title: Niels & Laura's Home
              type: entities
            style:
              margin: 0 8px
            type: custom:card-modder
        type: vertical-stack
    path: home
    title: Home
  - cards:
      - card:
          entities:
            - entity: sensor.time_niels_spent_at_home_the_past_7_days
              name: Niels was at home for
            - entity: sensor.time_laura_spent_at_home_the_past_7_days
              name: Laura was at home for
            - entity: sensor.time_spent_watching_tv
              name: The TV was on for
          show_header_toggle: false
          title: In the past 7 days
          type: entities
        style:
          margin: 0 8px
        type: custom:card-modder
    icon: mdi:poll-box
    path: reports
    title: Reports
  - cards:
      - cards:
          - card:
              entities:
                - automation.synchronise_scene_to_time_of_day
                - automation.handle_scene_override
                - label: Status
                  type: section
                - sensor.time_of_day
                - label: Thresholds
                  type: section
                - input_number.morning_threshold
                - input_number.day_threshold
                - input_number.afternoon_threshold
                - input_number.dusk_threshold
                - input_number.evening_threshold
                - label: Other automations
                  type: section
                - automation.trigger_morning_scene_at_fixed_time
                - automation.trigger_night_scene_at_fixed_time
              show_header_toggle: false
              title: Scenes
              type: entities
            style:
              margin: 0 8px
            type: custom:card-modder
          - card:
              entities:
                - automation.turn_on_receiver_when_audio_starts_playing
                - automation.turn_on_tv_when_media_starts_playing
                - automation.pause_music_when_turning_on_the_tv
                - automation.pause_media_through_harmony_remote
                - automation.play_media_through_harmony_remote
                - automation.pause_music_through_harmony_remote
                - automation.play_music_through_harmony_remote
              show_header_toggle: false
              title: Media
              type: entities
            style:
              margin: 0 8px
            type: custom:card-modder
        type: vertical-stack
    icon: mdi:settings
    path: settings
    title: Settings
