custom_header:
# compact_mode: true
title: " "
views:
  - cards:
      - type: vertical-stack
        cards:
          - card:
              show_header_toggle: false
              title: At a Glance
              type: entities
            entities:
              - icon: mdi:home-variant-outline
                name: Home state
                secondary: >-
                  {% if is_state('input_boolean.guest_mode', 'on') %}
                    Guest mode is on. Current scene is {{ states('sensor.current_scene') }}
                  {% elif is_state('sensor.current_scene', 'Away') %}

                  {% else %}
                    Current scene is {{ states('sensor.current_scene') }}
                  {% endif %}
                state: "{{ 'Occupied' if is_state('group.everyone', 'home') or is_state('input_boolean.guest_mode', 'on') else 'Empty' }}"
                type: custom:template-entity-row
              - active: "{{ is_state_attr('climate.living_room', 'hvac_action', 'heat') }}"
                icon: mdi:thermometer
                name: Living Room temperature
                secondary: >-
                  {% if is_state('climate.living_room', 'off') %}
                    Heating is turned off
                  {% elif is_state_attr('climate.living_room', 'hvac_action', 'idle') %}
                    Will heat if temperature drops below {{ state_attr('climate.living_room', 'temperature') }}°
                  {% else %}
                    Heating to {{ state_attr('climate.living_room', 'current_temperature') }}°
                  {% endif %}
                state: "{{ state_attr('climate.living_room', 'current_temperature') }}°"
                type: custom:template-entity-row
              - icon: mdi:alarm
                name: Next alarm
                secondary: >-
                  {% if state_attr('input_datetime.next_alarm', 'day') == now().day %}
                    Today is {{ 'a workday' if is_state('binary_sensor.today_is_a_workday', 'on') else 'an off day' }}
                  {% else %}
                    Tomorrow is {{ 'a workday' if is_state('binary_sensor.tomorrow_is_a_workday', 'on') else 'an off day' }}
                  {% endif %}
                state: >-
                  {% if state_attr('input_datetime.next_alarm', 'day') == now().day %}
                    {{ states('input_datetime.next_alarm') | as_timestamp | timestamp_custom('Today at %H:%M', true) }}
                  {% elif state_attr('input_datetime.next_alarm', 'day') == now().day + 1 %}
                    {{ states('input_datetime.next_alarm') | as_timestamp | timestamp_custom('Tomorrow at %H:%M', true) }}
                  {% else %}
                    {{ states('input_datetime.next_alarm') | as_timestamp | timestamp_custom('%A at %H:%M', true) }}
                  {% endif %}
                type: custom:template-entity-row
            filter:
              exclude:
                - entity_id: input_boolean.guest_mode
                - entity_id: input_boolean.vacation_mode
                - entity_id: "/\\w+\\d$/"
              include:
                - domain: input_boolean
                  entity_id: "/\\w*mode$/"
                  state: "on"
                - domain: light
                  state: "on"
            type: custom:auto-entities
          - card:
              show_header_toggle: false
              title: Quick access
              type: entities
            filter:
              exclude:
                - entity_id: input_boolean.guest_mode
                - entity_id: input_boolean.vacation_mode
              include:
                - entity_id: "/\\w*mode$/"
                  state: "off"
            type: custom:auto-entities
    icon: mdi:home-variant-outline
    path: home
    title: Home
  - cards:
      - type: vertical-stack
        cards:
          - entities:
              - input_boolean.guest_mode
              - input_boolean.vacation_mode
              - input_datetime.workday_alarm
              - input_datetime.off_day_alarm
              - type: section
                label: Time of day
              - input_number.morning_threshold
              - input_number.day_threshold
              - input_number.afternoon_threshold
              - input_number.early_evening_threshold
              - input_number.evening_threshold
              - type: section
                label: Illuminance
              - input_number.hallway_illuminance_threshold
              - input_number.kitchen_illuminance_threshold
              - type: section
                label: Zigbee
              - input_boolean.zigbee_permit_join
            show_header_toggle: false
            title: Settings
            type: entities
    icon: mdi:cog-outline
    path: settings
    title: Settings
