title: " "
views:
  - cards:
      - type: vertical-stack
        cards:
          - entities:
              - input_boolean.guest_mode
              - input_boolean.movie_mode
              - input_boolean.vacation_mode
              - type: section
                label: Kitchen illuminance
              - icon: mdi:brightness-6
                entity: sensor.kitchen_illuminance
                name: Current kitchen illuminance
                secondary: Currently, lights will {{ 'not' if is_state('binary_sensor.kitchen_sufficiently_lit', 'on') else '' }} turn on
                type: custom:template-entity-row
              - input_number.kitchen_illuminance_threshold
            show_header_toggle: false
            style:
              .: |
                ha-card {
                  background: transparent;
                  box-shadow: none;
                  transition: 0;
                }

                h1 {
                  padding: 24px 16px;
                }

                h1 .name {
                  font-size: 28px;
                  text-align: center;
                  width: 100%;
                }
              hui-section-row:
                $: |
                  .label {
                    color: var(--primary--text-color) !important;
                    font-family: 'Product Sans', Roboto;
                    font-weight: 600;
                  }
            title: General
            type: entities
    path: index
    title: General
  - cards:
      - type: vertical-stack
        cards:
          - entities:
              - entity: automation.update_lights_to_new_circadian_values
                icon: mdi:lightning-bolt-outline
                name: Update turned on lights automatically
                secondary_info: last-triggered
              - type: section
                label: Thresholds
              - sensor.filtered_upstairs_illuminance
              - input_number.setting_adaptive_lighting_max_illuminance
              - input_number.setting_adaptive_lighting_min_illuminance
              - type: section
                label: Light settings
              - input_number.setting_coolest_colour_temp
              - input_number.setting_warmest_colour_temp
              - input_number.setting_max_brightness
              - input_number.setting_min_brightness
              - input_number.setting_bedtime_brightness
            show_header_toggle: false
            style:
              .: |
                ha-card {
                  background: transparent;
                  box-shadow: none;
                  transition: 0;
                }

                h1 {
                  padding: 24px 16px;
                }

                h1 .name {
                  font-size: 28px;
                  text-align: center;
                  width: 100%;
                }
              hui-section-row:
                $: |
                  .label {
                    color: var(--primary--text-color) !important;
                    font-family: 'Product Sans', Roboto;
                    font-weight: 600;
                  }
            title: Adaptive lighting
            type: entities
    path: adaptive-lighting
    title: Adaptive lighting
  - cards:
      - type: vertical-stack
        cards:
          - entities:
              - action_name: Start
                entity: timer.heating_boost
                name: Temporarily boost the heating?
                tap_action:
                  action: call-service
                  service: timer.start
                  service_data:
                    entity_id: timer.work_mode_break
                type: button
              - type: section
                label: Settings
              - input_number.setting_heating_home_temperature
              - input_number.setting_heating_away_temperature
            show_header_toggle: false
            style:
              .: |
                ha-card {
                  background: transparent;
                  box-shadow: none;
                  transition: 0;
                }

                h1 {
                  padding: 24px 16px;
                }

                h1 .name {
                  font-size: 28px;
                  text-align: center;
                  width: 100%;
                }
              hui-section-row:
                $: |
                  .label {
                    color: var(--primary--text-color) !important;
                    font-family: 'Product Sans', Roboto;
                    font-weight: 600;
                  }
            title: Heating
            type: entities
    path: heating
    title: Heating
  - cards:
      - type: vertical-stack
        cards:
          - entities:
              - input_boolean.cooking_mode
              - type: section
                label: Schedule
              - input_datetime.cooking_start
              - input_datetime.cooking_end
              - type: section
                label: Notifications
              - input_boolean.setting_cooking_mode_notifications
            show_header_toggle: false
            style:
              .: |
                ha-card {
                  background: transparent;
                  box-shadow: none;
                  transition: 0;
                }

                h1 {
                  padding: 24px 16px;
                }

                h1 .name {
                  font-size: 28px;
                  text-align: center;
                  width: 100%;
                }
              hui-section-row:
                $: |
                  .label {
                    color: var(--primary--text-color) !important;
                    font-family: 'Product Sans', Roboto;
                    font-weight: 600;
                  }
            title: Cooking mode
            type: entities
    path: cooking-mode
    title: Cooking
  - cards:
      - type: vertical-stack
        cards:
          - entities:
              - entity: "input_boolean.{{ 'should_turn_on_bedtime_mode' if is_state('input_boolean.bedtime_mode', 'off') else  'bedtime_mode'}}"
                name: Bedtime mode
                toggle: true
                type: custom:template-entity-row
              - type: section
                label: Settings
              - type: custom:fold-entity-row
                clickable: true
                head:
                  icon: mdi:bed-outline
                  name: Bedtime
                  state: " "
                  type: custom:template-entity-row
                entities:
                  - entity: input_datetime.workday_bedtime
                    name: Workday
                  - entity: input_datetime.off_day_bedtime
                    name: Off day
              - type: custom:fold-entity-row
                clickable: true
                head:
                  icon: mdi:alarm
                  name: Wake up
                  state: " "
                  type: custom:template-entity-row
                entities:
                  - entity: input_datetime.workday_alarm
                    name: Workday
                  - entity: input_datetime.off_day_alarm
                    name: Off day
              - type: section
                label: Notifications
              - entity: input_boolean.setting_bedtime_notifications
                name: Get notifications about bedtime mode
            show_header_toggle: false
            style:
              .: |
                ha-card {
                  background: transparent;
                  box-shadow: none;
                  transition: 0;
                }

                h1 {
                  padding: 24px 16px;
                }

                h1 .name {
                  font-size: 28px;
                  text-align: center;
                  width: 100%;
                }
              hui-section-row:
                $: |
                  .label {
                    color: var(--primary--text-color) !important;
                    font-family: 'Product Sans', Roboto;
                    font-weight: 600;
                  }
            title: Bedtime
            type: entities
    path: bedtime-mode
    title: Bedtime
