title: " "
views:
  - path: index
    icon: mdi:settings-outline
    theme: material-light-soft
    cards:
      - type: vertical-stack
        cards:
          # - type: custom:google-home-settings
          #   cards: []
          # - type: entities
          #   entities:
          #     - input_datetime.workday_alarm
          #     - input_datetime.off_day_alarm
          #     - input_number.morning_threshold
          #     - input_number.day_threshold
          #     - input_number.afternoon_threshold
          #     - input_number.early_evening_threshold
          #     - input_number.evening_threshold
          # - type: entities
          #   entities:
          #     - input_boolean.zigbee_permit_join
          - type: custom:layout-card
            layout: grid
            gridcols: auto 48px
            cards:
              - type: markdown
                gridcol: 1 / 2
                content: |
                  {% if now().hour < 5 %}
                    ## Good night, {{ user }}
                  {% elif now().hour < 12 %}
                    ## Good morning, {{ user }}
                  {% elif now().hour < 18 %}
                    ## Good afternoon, {{ user }}
                  {% else %}
                    ## Have a nice evening, {{ user.split(' ')[0] }}
                  {% endif %}
                style: |
                  ha-card {
                    align-items: center;
                    background: transparent;
                    box-shadow: none;
                    display: flex;
                    font-family: 'Product Sans';
                    height: 100%;
                  }

                  h2 {
                    font-weight: 500;
                  }
              - type: glance
                gridcol: 2 / 2
                entities:
                  - person.niels
                show_name: false
                show_state: false
                style: |
                  ha-card {
                    background: transparent;
                    box-shadow: none;
                    height: 100%;
                  }
          - type: markdown
            content: |
              ### {{ now().strftime('%B %-d') }}
            style: |
              ha-card {
                background: transparent;
                box-shadow: none;
                font-family: 'Product Sans';
              }

              h3 {
                font-size: 1.25rem;
                font-weight: 500;
              }
          - type: custom:simple-weather-card
            entity: weather.br_unknown_station
            name: in Utrecht
            backdrop:
              day: rgba(249, 233, 181)
              text: var(--app-header-text-color)
              night: rgba(76, 87, 110)
              fade: true
            style: |
              ha-card {
                margin: 12px;
              }
          - type: markdown
            content: |
              ### At a Glance
            style: |
              ha-card {
                background: transparent;
                box-shadow: none;
                font-family: 'Product Sans';
                margin: 12px;
              }

              h3 {
                font-size: 1.25rem;
                font-weight: 500;
              }
          - type: entities
            entities:
              - sensor.time_of_day
              - climate.living_room
            style: |
              ha-card {
                margin: 14px;
              }