title: Settings
path: settings
icon: mdi:settings-outline
# panel: true
cards:
  - type: vertical-stack
    cards:
      # - type: custom:google-home-settings
      #   cards: []
      - type: entities
        entities:
          - input_number.morning_threshold
          - input_number.day_threshold
          - input_number.afternoon_threshold
          - input_number.early_evening_threshold
          - input_number.evening_threshold