automation:
  - alias: Toggle Living Room pendant through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/living_room_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'left' }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.living_room_pendant

  - alias: Toggle Living Room spots through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/living_room_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'right' }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.living_room_spots
          transition: 1

  - alias: Set Living Room spots to full brightness through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/living_room_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'right_double' }}"
    action:
      - service: light.turn_on
        data:
          brightness: 255
          color_temp: 344
          entity_id: light.living_room_spots
          transition: 1

group:
  living_room_lights:
    entities:
      - light.living_room_pendant
      - light.living_room_spots
    icon: mdi:lightbulb-group-outline
    name: Living Room lights

homeassistant:
  customize:
    binary_sensor.living_room_window:
      device_class: window

light:
  - platform: switch
    name: Living Room pendant
    entity_id: switch.power_outlet_2
  - platform: mqtt
    brightness: true
    color_temp: true
    command_topic: "zigbee2mqtt/living_room_spots/set"
    name: Living Room spots
    schema: json
    state_topic: "zigbee2mqtt/living_room_spots"