automation:
  - alias: Set light.bathroom_spots
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when automations are reloaded
      - platform: event
        event_type: automation_reloaded

      # Trigger immediately when current scene changes to a state we're interested in
      - platform: state
        entity_id: sensor.current_scene
        to: Night

      # Trigger immediately when current scene changes from a state we're interested in
      - platform: state
        entity_id: sensor.current_scene
        from: Night

      # Trigger immediately when the bathroom is occupied
      - platform: state
        entity_id: binary_sensor.bathroom_occupied
        to: "on"

      # Trigger a minute after the bathroom is no longer occupied
      - platform: state
        entity_id: binary_sensor.bathroom_occupied
        to: "off"
        for:
          minutes: 1
    action:
      - service: light.turn_on
        data:
          entity_id: light.bathroom_spots
          brightness: >-
            {% set isOccupied = is_state('binary_sensor.bathroom_occupied', 'on') %}
            {% set isNight = is_state('sensor.current_scene', 'Night') %}

            {% if isOccupied and not isNight %}
              255
            {% elif isOccupied and isNight %}
              1
            {% else %}
              0
            {% endif %}
          transition: 0.5

binary_sensor:
  - platform: template
    sensors:
      bathroom_occupied:
        device_class: occupancy
        friendly_name: Bathroom occupied
        value_template: "{{ is_state('group.bathroom_occupied', 'on') }}"

climate:
  - platform: mqtt
    name: Bathroom
    modes:
      - "off"
      - auto
    current_temperature_template: "{{ value_json.temperature }}"
    current_temperature_topic: zigbee2mqtt/bathroom_temperature_pressure_and_humidity_sensor
    json_attributes_topic: zigbee2mqtt/bathroom_temperature_pressure_and_humidity_sensor
    json_attributes_template: >-
      {% set attributes = {
        "current_humidity": value_json.humidity,
        "current_pressure": value_json.pressure
      } %}

      {{ attributes | to_json }}

group:
  bathroom_occupied:
    name: Bathroom occupied
    entities:
      - binary_sensor.bathroom_motion
      # - binary_sensor.shower_in_use

light:
  - platform: mqtt
    brightness: true
    command_topic: zigbee2mqtt/bathroom_spots/set
    name: Bathroom spots
    schema: json
    state_topic: zigbee2mqtt/bathroom_spots

sensor:
  - platform: mqtt
    name: Bathroom humidity
    state_topic: zigbee2mqtt/bathroom_temperature_pressure_and_humidity_sensor
    unit_of_measurement: "%"
    value_template: "{{ value_json.humidity }}"
  - platform: mqtt
    name: Bathroom temperature
    state_topic: zigbee2mqtt/bathroom_temperature_pressure_and_humidity_sensor
    unit_of_measurement: "°C"
    value_template: "{{ value_json.temperature }}"