automation:
  - alias: Notify when humidity in Bedroom reaches high levels
    description: Send a notification suggesting to turn on the dehumidifier in this area when the humidity is more than 80%
    trigger:
      # Trigger immediately when the humidity goes above 79%
      - platform: numeric_state
        entity_id: sensor.bedroom_humidity
        above: 79
    action:
      - service: notify.all_devices
        data:
          title: "High humidity in Bedroom"
          message: "Consider turning on the dehumidifier{{ ' when you get home' if is_state('sensor.current_scene', 'Away') else '' }}"
          data:
            channel: Suggestions

  - alias: Notify when humidity in Bedroom reaches normal levels
    description: Send a notification suggesting to turn off the dehumidifier in this area when the humidity is back down to 60%
    trigger:
      # Trigger immediately when the humidity drops below 61%
      - platform: numeric_state
        entity_id: sensor.bedroom_humidity
        below: 61
    action:
      - service: notify.all_devices
        data:
          title: "Humidity returned to normal in Bedroom"
          message: "Consider turning off the dehumidifier{{ ' when you get home' if is_state('sensor.current_scene', 'Away') else '' }}"
          data:
            channel: Suggestions

climate:
  - platform: mqtt
    name: Bedroom
    modes:
      - "off"
      - auto
    current_temperature_template: "{{ value_json.temperature }}"
    current_temperature_topic: zigbee2mqtt/bedroom_temperature_pressure_and_humidity_sensor
    json_attributes_topic: zigbee2mqtt/bedroom_temperature_pressure_and_humidity_sensor
    json_attributes_template: >-
      {% set attributes = {
        "current_humidity": value_json.humidity,
        "current_pressure": value_json.pressure
      } %}

      {{ attributes | to_json }}
