climate:
  - platform: mqtt
    name: Bedroom
    modes:
      - "off"
      - auto
    current_temperature_template: "{{ value_json.temperature }}"
    current_temperature_topic: zigbee2mqtt/bedroom_temperature_pressure_and_humidity_sensor
    json_attributes_topic: zigbee2mqtt/bedroom_temperature_pressure_and_humidity_sensor
    json_attributes_template: >-
      {% set attributes = {
        "current_humidity": value_json.humidity,
        "current_pressure": value_json.pressure
      } %}

      {{ attributes | to_json }}

light:
  - platform: mqtt
    brightness: true
    command_topic: zigbee2mqtt/bedroom_spots/set
    name: Bedroom spots
    schema: json
    state_topic: zigbee2mqtt/bedroom_spots

sensor:
  - platform: mqtt
    name: Bedroom humidity
    state_topic: zigbee2mqtt/bedroom_temperature_pressure_and_humidity_sensor
    unit_of_measurement: "%"
    value_template: "{{ value_json.humidity }}"
  - platform: mqtt
    name: Bedroom temperature
    state_topic: zigbee2mqtt/bedroom_temperature_pressure_and_humidity_sensor
    unit_of_measurement: "°C"
    value_template: "{{ value_json.temperature }}"