automation:
  - alias: Set light.hallway_spots
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when current scene changes to a state we're interested in
      - platform: state
        entity_id: sensor.current_scene
        to: Night

      # Trigger immediately when current scene changes from a state we're interested in
      - platform: state
        entity_id: sensor.current_scene
        from: Night

      # Trigger immediately when the door opens or closes
      - platform: state
        entity_id: binary_sensor.hallway_door
        to:
          - "on"
          - "off"

      # Trigger immediately when motion detection changes
      - platform: state
        entity_id: binary_sensor.hallway_motion
        to:
          - "on"
          - "off"
    action:
      - service: light.turn_on
        data:
          entity_id: light.hallway_spots
          brightness: >-
            {% set isDark = is_state('binary_sensor.hallway_sufficiently_lit', 'off') %}
            {% set isDoorOpen = is_state('binary_sensor.hallway_door', 'on') %}
            {% set isMotion = is_state('binary_sensor.hallway_motion', 'on') %}
            {% set isNight = is_state('sensor.current_scene', 'Night') %}

            {% if isDoorOpen or (isMotion and not isNight) %}
              255
            {% elif isMotion and isNight %}
              1
            {% else %}
              0
            {% endif %}
          transition: 0.5

binary_sensor:
  - platform: template
    sensors:
      hallway_sufficiently_lit:
        device_class: light
        friendly_name: Hallway is sufficiently lit
        value_template: "{{ state_attr('binary_sensor.hallway_motion', 'illuminance') | float > states('input_number.hallway_illuminance_threshold') | float }}"

input_number:
  hallway_illuminance_threshold:
    icon: mdi:tune
    max: 100
    min: 0
    mode: box
    name: Hallway illuminance threshold
    step: 1

light:
  - platform: mqtt
    brightness: true
    command_topic: "zigbee2mqtt/hallway_spots/set"
    name: Hallway spots
    schema: json
    state_topic: "zigbee2mqtt/hallway_spots"
