automation:
  - alias: Set light.hallway_spots
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when automations are reloaded
      - platform: event
        event_type: automation_reloaded

      # Trigger immediately when current scene changes to a state we're interested in
      - platform: state
        entity_id: sensor.current_scene
        to: Night

      # Trigger immediately when current scene changes from a state we're interested in
      - platform: state
        entity_id: sensor.current_scene
        from: Night

      # Trigger immediately when the door opens or closes
      - platform: state
        entity_id: binary_sensor.hallway_door
        to:
          - "on"
          - "off"

      # Trigger immediately when motion is no longer detected in the hallway
      - platform: state
        entity_id: binary_sensor.hallway_motion
        to:
          - "on"
          - "off"
    action:
      - service: light.turn_on
        data:
          entity_id: light.hallway_spots
          brightness: >-
            {% set isDoorOpen = is_state('binary_sensor.hallway_door', 'on') %}
            {% set isMotion = is_state('binary_sensor.hallway_motion', 'on') %}
            {% set isNight = is_state('sensor.current_scene', 'Night') %}

            {% if isDoorOpen or (isMotion and not isNight) %}
              255
            {% else %}
              0
            {% endif %}
          transition: 0.5

binary_sensor:
  - platform: mqtt
    device_class: door
    name: Hallway door
    payload_off: true
    payload_on: false
    state_topic: zigbee2mqtt/hallway_door_sensor
    value_template: "{{ value_json.contact }}"
  - platform: mqtt
    device_class: motion
    name: Hallway motion
    payload_off: false
    payload_on: true
    state_topic: zigbee2mqtt/hallway_motion_sensor
    value_template: "{{ value_json.occupancy }}"

light:
  - platform: mqtt
    brightness: true
    command_topic: zigbee2mqtt/hallway_spots/set
    name: Hallway spots
    schema: json
    state_topic: zigbee2mqtt/hallway_spots

sensor:
  - platform: mqtt
    name: Hallway illuminance
    state_topic: zigbee2mqtt/hallway_motion_sensor
    unit_of_measurement: lm
    value_template: "{{ value_json.illuminance }}"