automation:
  - alias: Set light.kitchen_mood_lighting
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when automations are reloaded
      - platform: event
        event_type: automation_reloaded

      # Trigger immediately when current scene changes
      - platform: state
        entity_id: sensor.current_scene
        to: "*"
    action:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_mood_lighting
          brightness: >-
            {% set isAway = is_state('sensor.current_scene', 'Away') %}
            {% set isDay = is_state('sensor.current_scene', 'Day') %}
            {% set isNight = is_state('sensor.current_scene', 'Night') %}

            {{ 0 if isAway or isDay or isNight else 255 }}

  - alias: Set light.kitchen_spots
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when current scene changes
      - platform: state
        entity_id: sensor.current_scene
        to:
          - Morning
          - Day
          - Night

      # Trigger immediately when motion detection changes
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        to:
          - "on"
          - "off"

      # Trigger immediately when the illuminance threshold is changed
      - platform: state
        entity_id: input_number.kitchen_illuminance_threshold
        to: "*"

      # Trigger immediately when bright mode is toggled
      - platform: state
        entity_id: input_boolean.kitchen_bright_mode
        to:
          - "on"
          - "off"

      # Trigger immediately when cooking mode is toggled
      - platform: state
        entity_id: input_boolean.cooking_mode
        to:
          - "on"
          - "off"
    action:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_spots
          brightness: >-
            {% set isMotion = is_state('binary_sensor.kitchen_motion', 'on') %}
            {% set isBright = is_state('input_boolean.kitchen_bright_mode', 'on') %}
            {% set isCooking = is_state('input_boolean.cooking_mode', 'on') %}
            {% set isDark = is_state('binary_sensor.kitchen_motion', 'on') %}
            {% set isNight = is_state('sensor.current_scene', 'Night') %}
            {% set isMorning = is_state('sensor.current_scene', 'Morning') %}

            {% if isNight and isMotion %}
              1
            {% elif isMorning or isBright or isCooking or (isDark and isMotion) %}
              255
            {% else %}
              0
            {% endif %}
          transition: 0.5

  - alias: Set light.kitchen_worktop
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when cooking mode is toggled
      - platform: state
        entity_id: input_boolean.cooking_mode
        to:
          - "on"
          - "off"
    action:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_worktop
          brightness: >-
            {% set isCooking = is_state('input_boolean.cooking_mode', 'on') %}

            {{ 255 if isCooking else 0 }}
          transition: 0.5

  - alias: Toggle cooking mode
    trigger:
      # Trigger immediately when the kitchen wall switch's right button is pressed
      - platform: mqtt
        topic: zigbee2mqtt/kitchen_switch/action
        payload: single_right
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.cooking_mode
      - service: input_boolean.turn_off
        entity_id: input_boolean.kitchen_bright_mode

  - alias: Toggle kitchen bright mode
    trigger:
      # Trigger immediately when the kitchen wall switch's left button is pressed
      - platform: mqtt
        topic: zigbee2mqtt/kitchen_switch/action
        payload: single_left
    action:
      - condition: state
        entity_id: input_boolean.cooking_mode
        state: "off"
      - service: input_boolean.toggle
        entity_id: input_boolean.kitchen_bright_mode

input_boolean:
  cooking_mode:
    icon: mdi:chef-hat
    name: Cooking mode
  kitchen_bright_mode:
    icon: mdi:brightness-7
    name: Bright mode (Kitchen)

input_number:
  kitchen_illuminance_threshold:
    icon: mdi:tune
    max: 100
    min: 0
    mode: box
    name: Kitchen illuminance threshold
    step: 1

light:
  - platform: mqtt
    brightness: true
    command_topic: "zigbee2mqtt/kitchen_spots/set"
    name: Kitchen spots
    schema: json
    state_topic: "zigbee2mqtt/kitchen_spots"
  - platform: switch
    name: Kitchen mood lighting
    entity_id: switch.power_outlet_1
