automation:
  - alias: Set correct Harmony activity
    description: Sets the correct Harmony Hub activity
    mode: restart
    trigger:
      # Trigger immediately when the amplifier is ready
      - platform: state
        entity_id: binary_sensor.amplifier_ready
        from: "off"
        to: "on"
    action:
      # only continue if the Harmony Hub does not currently have an active activity
      # and it's not starting an activity
      - condition: and
        conditions:
          - condition: state
            entity_id: remote.harmony_hub
            attribute: current_activity
            state: PowerOff
          - condition: state
            entity_id: remote.harmony_hub
            attribute: activity_starting
            state: "null"

      # Set the correct Harmony Hub activity
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: >-
            {% set currentSource = state_attr('media_player.amplifier', 'source') %}
            {% set sourceActivityMap = {
              "Opt2": "Play a Game",
              "Opt2": "Watch TV",
              "Wireless": "Listen to Music",
              "Phono": "Listen to Vinyl"
            } %}

            {{ sourceActivityMap[currentSource] }}

  - alias: Set correct input on amplifier
    description: Sets the correct input on the amplifier when a Harmony activity is activated
    mode: restart
    trigger:
      # Trigger when the currently active activity is in the list of possible activities (meaning we switched to on or to a differen activity)
      - platform: template
        value_template: "{{ state_attr('remote.harmony_hub', 'activity_starting') in state_attr('remote.harmony_hub', 'activity_list') }}"
    action:
      # Wait until the amplifier is marked as ready
      - wait_template: "{{ is_state('binary_sensor.amplifier_ready', 'on') }}"

      # Switch to the correct input
      - service: media_player.select_source
        data:
          entity_id: media_player.amplifier
          source: >-
            {% set currentActivity = state_attr('remote.harmony_hub', 'current_activity') %}
            {% set activitySourceMap = {
              "Play a Game": "Opt2",
              "Watch TV": "Opt2",
              "Listen to Music": "Wireless",
              "Listen to Vinyl": "Phono"
            } %}

            {{ activitySourceMap[currentActivity] }}

  - alias: Set light.living_room_pendant
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when automations are reloaded
      - platform: event
        event_type: automation_reloaded

      # Trigger immediately when current scene changes
      - platform: state
        entity_id: sensor.current_scene
        to: "*"
    action:
      - service: light.turn_on
        data:
          entity_id: light.living_room_pendant
          brightness: >-
            {% set isAway = is_state('sensor.current_scene', 'Away') %}
            {% set isDay = is_state('sensor.current_scene', 'Day') %}
            {% set isNight = is_state('sensor.current_scene', 'Night') %}

            {{ 0 if isAway or isDay or isNight else 255 }}

  - alias: Set light.living_room_spots
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when automations are reloaded
      - platform: event
        event_type: automation_reloaded

      # Trigger immediately when current scene changes
      - platform: state
        entity_id: sensor.current_scene
        to: "*"

      # Trigger immediately when bright mode is toggled
      - platform: state
        entity_id: input_boolean.living_room_bright_mode
        to:
          - "on"
          - "off"
    action:
      - service: light.turn_on
        data:
          entity_id: light.living_room_spots
          brightness: >-
            {% set isAway = is_state('sensor.current_scene', 'Away') %}
            {% set isBright = is_state('input_boolean.living_room_bright_mode', 'on') %}
            {% set isEvening = is_state('sensor.current_scene', 'Evening') %}
            {% set isMorning = is_state('sensor.current_scene', 'Morning') %}

            {% if isBright %}
              255
            {% elif isMorning or isEvening %}
              125
            {% else %}
              0
            {% endif %}
          color_temp: >-
            {% set isBright = is_state('input_boolean.living_room_bright_mode', 'on') %}

            {{ 380 if isBright else 475 }}
          transition: "{{ 0.5 if is_state('light.living_room_spots', 'off') else 2 }}"

  - alias: Set living room climate state
    description: Sets the thermostat to the correct temperature and turns it off if a door or window is open
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when automations are reloaded
      - platform: event
        event_type: automation_reloaded

      # Trigger immediately when current scene changes
      - platform: state
        entity_id: sensor.current_scene
        to: "*"

      # Trigger after kitchen door has been open for 30 seconds
      - platform: state
        entity_id: binary_sensor.kitchen_door
        to: "on"
        for:
          seconds: 30

      # Trigger immediately when kitchen door closes
      - platform: state
        entity_id: binary_sensor.kitchen_door
        to: "off"

      # Trigger after living room window has been open for 30 seconds
      - platform: state
        entity_id: binary_sensor.living_room_window
        to: "on"
        for:
          seconds: 30

      # Trigger immediately when living room window closes
      - platform: state
        entity_id: binary_sensor.living_room_window
        to: "off"
    action:
      - service: >-
          {% set shouldTurnOff = is_state('binary_sensor.kitchen_door', 'on') or is_state('binary_sensor.living_room_window', 'on') %}

          climate.turn_{{ 'off' if shouldTurnOff else 'on' }}
        data:
          entity_id: climate.living_room
      - service: climate.set_temperature
        data:
          entity_id: climate.living_room
          temperature: >-
            {% set isAway = is_state('sensor.current_scene', 'Away') %}
            {% set isNight = is_state('sensor.current_scene', 'Night') %}

            {{ 16 if isAway or isNight else 19 }}

  - alias: Set switch.power_outlet_3
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when automations are reloaded
      - platform: event
        event_type: automation_reloaded

      # Trigger immediately when the amplifier turns on or off
      - platform: state
        entity_id: media_player.amplifier
        to:
          - "on"
          - "off"
    action:
      - service: "switch.turn_{{ states('media_player.amplifier') }}"
        data:
          entity_id: switch.power_outlet_3

binary_sensor:
  - platform: template
    sensors:
      amplifier_ready:
        friendly_name: Amplifier ready
        delay_on:
          seconds: 7
        value_template: "{{ is_state('media_player.amplifier', 'on') }}"

input_boolean:
  living_room_bright_mode:
    icon: mdi:brightness-7
    name: Bright mode (Living Room)

light:
  - platform: mqtt
    brightness: true
    color_temp: true
    command_topic: "zigbee2mqtt/living_room_spots/set"
    name: Living room spots
    schema: json
    state_topic: "zigbee2mqtt/living_room_spots"
  - platform: switch
    name: Living Room pendant
    entity_id: switch.power_outlet_2

media_player:
  - platform: nadtcp2
    name: Amplifier
    host: !secret nad_amplifier_ip
    volume_step: 2
