automation:
  - alias: Set correct Harmony activity
    description: Sets the correct Harmony Hub activity when one of the media devices turns on on its own
    mode: restart
    trigger:
      # Trigger immediately when the amplifier is ready
      - platform: state
        entity_id: binary_sensor.amplifier_ready
        from: "off"
        to: "on"
    action:
      # only continue if the Harmony Hub does not currently have an active activity
      # and it's not starting an activity
      - condition: template
        value_template: "{{ is_state_attr('remote.living_room_harmony_hub', 'current_activity', 'PowerOff') and state_attr('remote.living_room_harmony_hub', 'activity_starting') == None }}"

      # Set the correct Harmony Hub activity
      - service: remote.turn_on
        data:
          entity_id: remote.living_room_harmony_hub
          activity: >-
            {% set currentSource = state_attr('media_player.amplifier', 'source') %}
            {% set xBoxIsOn = is_state('media_player.xbox_one', 'on') %}

            {% if currentSource == 'Wireless' %}
              Listen to Music
            {% elif currentSource == 'Phono' %}
              Listen to Vinyl
            {% elif currentSource == 'Opt2' and xBoxIsOn %}
              Play a Game
            {% elif currentSource == 'Opt2' and not xBoxIsOn %}
              Watch TV
            {% else %}
            {% endif %}

  - alias: Set correct input on amplifier
    description: Sets the correct input on the amplifier when a Harmony activity is activated
    mode: restart
    trigger:
      # Trigger when the currently active activity is in the list of possible activities (meaning we switched to on or to a different activity)
      - platform: template
        value_template: "{{ state_attr('remote.living_room_harmony_hub', 'activity_starting') in state_attr('remote.living_room_harmony_hub', 'activity_list') }}"
    action:
      # Wait until the amplifier is marked as ready
      - wait_template: "{{ is_state('binary_sensor.amplifier_ready', 'on') }}"

      # Switch to the correct input
      - service: media_player.select_source
        data:
          entity_id: media_player.amplifier
          source: >-
            {% set currentActivity = state_attr('remote.living_room_harmony_hub', 'current_activity') %}
            {% set activitySourceMap = {
              "Play a Game": "Opt2",
              "Watch TV": "Opt2",
              "Listen to Music": "Wireless",
              "Listen to Vinyl": "Phono"
            } %}

            {{ activitySourceMap[currentActivity] }}

  - alias: Set light.living_room_pendant
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when automations are reloaded
      - platform: event
        event_type: automation_reloaded

      # Trigger immediately when current scene changes
      - platform: state
        entity_id: sensor.current_scene
        to: "*"

      # Trigger immediately when movie mode is toggled
      - platform: state
        entity_id: input_boolean.movie_mode
        to:
          - "on"
          - "off"
    action:
      - service: light.turn_on
        data:
          entity_id: light.living_room_pendant
          brightness: >-
            {% set isAway = is_state('sensor.current_scene', 'Away') %}
            {% set isDay = is_state('sensor.current_scene', 'Day') %}
            {% set isMovie = is_state('input_boolean.movie_mode', 'on') %}
            {% set isNight = is_state('sensor.current_scene', 'Night') %}

            {{ 0 if isAway or isDay or isMovie or isNight else 255 }}

  - alias: Set light.living_room_spots
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when automations are reloaded
      - platform: event
        event_type: automation_reloaded

      # Trigger immediately when current scene changes
      - platform: state
        entity_id: sensor.current_scene
        to: "*"

      # Trigger immediately when bright mode is toggled
      - platform: state
        entity_id: input_boolean.living_room_bright_mode
        to:
          - "on"
          - "off"

      # Trigger immediately when movie mode is toggled
      - platform: state
        entity_id: input_boolean.movie_mode
        to:
          - "on"
          - "off"

      # Trigger immediately when Living Room TV playback changes
      - platform: state
        entity_id: media_player.living_room_android_tv
        to:
          - paused
          - playing
    action:
      - service: light.turn_on
        data:
          entity_id: light.living_room_spots
          brightness: >-
            {% set isAway = is_state('sensor.current_scene', 'Away') %}
            {% set isBright = is_state('input_boolean.living_room_bright_mode', 'on') %}
            {% set isEvening = is_state('sensor.current_scene', 'Evening') %}
            {% set isMediaPaused = is_state('media_player.living_room_android_tv', 'paused') %}
            {% set isMorning = is_state('sensor.current_scene', 'Morning') %}
            {% set isMovie = is_state('input_boolean.movie_mode', 'on') %}

            {% if isBright %}
              255
            {% elif isMovie and not isMediaPaused %}
              30
            {% elif isMorning or isEvening or (isMovie and isMediaPaused) %}
              125
            {% else %}
              0
            {% endif %}
          color_temp: >-
            {% set isBright = is_state('input_boolean.living_room_bright_mode', 'on') %}

            {{ 350 if isBright else 475 }}
          transition: "{{ 0.5 if is_state('input_boolean.living_room_bright_mode', 'on') else 2 }}"

  - alias: Set living room climate state
    description: Sets the thermostat to the correct temperature and turns it off if a door or window is open
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when automations are reloaded
      - platform: event
        event_type: automation_reloaded

      # Trigger immediately when current scene changes
      - platform: state
        entity_id: sensor.current_scene
        to: "*"

      # Trigger after kitchen door has been open for 30 seconds
      - platform: state
        entity_id: binary_sensor.kitchen_door
        to: "on"
        for:
          seconds: 30

      # Trigger immediately when kitchen door closes
      - platform: state
        entity_id: binary_sensor.kitchen_door
        to: "off"

      # Trigger after living room window has been open for 30 seconds
      - platform: state
        entity_id: binary_sensor.living_room_window
        to: "on"
        for:
          seconds: 30

      # Trigger immediately when living room window closes
      - platform: state
        entity_id: binary_sensor.living_room_window
        to: "off"
    action:
      - service: >-
          {% set shouldTurnOff = is_state('binary_sensor.kitchen_door', 'on') or is_state('binary_sensor.living_room_window', 'on') %}

          climate.turn_{{ 'off' if shouldTurnOff else 'on' }}
        data:
          entity_id: climate.living_room
      - service: climate.set_temperature
        data:
          entity_id: climate.living_room
          temperature: >-
            {% set isAway = is_state('sensor.current_scene', 'Away') %}
            {% set isNight = is_state('sensor.current_scene', 'Night') %}

            {{ 16 if isAway or isNight else 19 }}

  - alias: Set switch.power_outlet_3
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when automations are reloaded
      - platform: event
        event_type: automation_reloaded

      # Trigger immediately when the amplifier turns on or off
      - platform: state
        entity_id: media_player.amplifier
        to:
          - "on"
          - "off"
    action:
      - service: "switch.turn_{{ states('media_player.amplifier') }}"
        data:
          entity_id: switch.power_outlet_3

binary_sensor:
  - platform: mqtt
    device_class: window
    name: Living Room window
    payload_off: true
    payload_on: false
    state_topic: zigbee2mqtt/living_room_window_sensor
    value_template: "{{ value_json.contact }}"
  - platform: template
    sensors:
      amplifier_ready:
        friendly_name: Amplifier ready
        delay_on:
          seconds: 7
        value_template: "{{ is_state('media_player.amplifier', 'on') }}"

input_boolean:
  living_room_bright_mode:
    icon: mdi:brightness-7
    name: Bright mode (Living Room)
  movie_mode:
    icon: mdi:filmstrip
    name: Movie mode

light:
  - platform: mqtt
    command_topic: zigbee2mqtt/power_outlet_2/set
    name: Living room pendant
    schema: json
    state_topic: zigbee2mqtt/power_outlet_2
  - platform: mqtt
    brightness: true
    color_temp: true
    command_topic: zigbee2mqtt/living_room_spots/set
    name: Living room spots
    schema: json
    state_topic: zigbee2mqtt/living_room_spots

media_player:
  - platform: androidtv
    name: Living Room Android TV
    host: !secret living_room_tv_ip
  - platform: nadtcp2
    name: Amplifier
    host: !secret nad_amplifier_ip
    volume_step: 2

remote:
  - platform: harmony
    name: Living Room Harmony Hub
    host: !secret living_room_harmony_hub_ip

switch:
  - platform: mqtt 
    command_topic: zigbee2mqtt/power_outlet_3/set
    name: Power outlet 3
    state_topic: zigbee2mqtt/power_outlet_3
    value_template: "{{ value_json.state }}"