automation:
  - alias: Set living room climate state
    description: Sets the thermostat to the correct temperature and turns it off if a door or window is open
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when automations are reloaded
      - platform: event
        event_type: automation_reloaded

      # Trigger immediately when current scene changes
      - platform: state
        entity_id: sensor.current_scene
        to: "*"

      # Trigger after kitchen door has been open for 30 seconds
      - platform: state
        entity_id: binary_sensor.kitchen_door
        to: "on"
        for:
          seconds: 30

      # Trigger immediately when kitchen door closes
      - platform: state
        entity_id: binary_sensor.kitchen_door
        to: "off"

      # Trigger after living room window has been open for 30 seconds
      - platform: state
        entity_id: binary_sensor.living_room_window
        to: "on"
        for:
          seconds: 30

      # Trigger immediately when living room window closes
      - platform: state
        entity_id: binary_sensor.living_room_window
        to: "off"
    action:
      - service: >-
          {% set shouldTurnOff = is_state('binary_sensor.kitchen_door', 'on') or is_state('binary_sensor.living_room_window', 'on') %}

          climate.turn_{{ 'off' if shouldTurnOff else 'on' }}
        data:
          entity_id: climate.living_room
      - service: climate.set_temperature
        data:
          entity_id: climate.living_room
          temperature: >-
            {% set isAway = is_state('sensor.current_scene', 'Away') %}
            {% set isNight = is_state('sensor.current_scene', 'Night') %}

            {{ 16 if isAway or isNight else 19 }}
