automation:
  - alias: Set office lights state
    description: Turns on or off the correct office lights
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when current scene changes
      - platform: state
        entity_id: sensor.current_scene
        to: "*"

      # Trigger immediately when work mode is toggled
      - platform: state
        entity_id: input_boolean.work_mode
        to:
          - "on"
          - "off"

      # Trigger immediately when motion detection changes
      - platform: state
        entity_id: binary_sensor.office_motion
        to:
          - "on"
          - "off"
    action:
      - service: script.set_office_lights_state

input_boolean:
  work_mode:
    icon: mdi:briefcase-outline
    name: Work mode

light:
  - platform: mqtt
    brightness: true
    command_topic: "zigbee2mqtt/office_spots/set"
    name: Office spots
    schema: json
    state_topic: "zigbee2mqtt/office_spots"

script:
  set_office_lights_state:
    alias: Set office lights state
    mode: restart
    sequence:
      - choose:
          # IF work mode is enabled
          - conditions:
              - condition: state
                entity_id: input_boolean.work_mode
                state: "on"
            sequence:
              - service: scene.apply
                data:
                  entities:
                    light.office_desk:
                      brightness: 255
                      state: on
                    light.office_spots:
                      brightness: 255
                      state: on
                    light.office_worktop:
                      brightness: 255
                      state: on
                  transition: 0.5

          # IF motion is detected
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_motion
                state: "on"
            sequence:
              - choose:
                  # IF "Night" scene is active
                  - conditions:
                      - condition: state
                        entity_id: sensor.current_scene
                        state: Night
                    sequence:
                      - service: scene.apply
                        data:
                          entities:
                            light.office_desk:
                              brightness: 1
                              state: on
                          transition: 0.5
                # ELSE (any other scene is active)
                default:
                  - service: scene.apply
                    data:
                      entities:
                        light.office_desk: off
                        light.office_spots:
                          brightness: 255
                          state: on
                        light.office_worktop: off
                      transition: 0.5

        default:
          - service: scene.apply
            data:
              entities:
                light.office_desk: off
                light.office_spots: off
                light.office_worktop: off
              transition: 1
