automation:
  - alias: Set toilet lights state
    description: Turns on the toilet lights when it's occupied and off when it's not
    mode: restart
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when current scene changes
      - platform: state
        entity_id: sensor.current_scene

      # Trigger immediately when the toilet door is opened
      - platform: state
        entity_id: binary_sensor.toilet_door
        to: "on"

      # Trigger immediately when the toilet door is closed
      - platform: state
        entity_id: binary_sensor.toilet_door
        to: "off"

      # Trigger immediately when motion is detected
      - platform: state
        entity_id: binary_sensor.toilet_motion
        to: "on"

      # Trigger a minute after motion is no longer detected
      - platform: state
        entity_id: binary_sensor.toilet_motion
        to: "off"
        for:
          minutes: 1
    action:
      - service: script.set_toilet_lights_state

script:
  set_toilet_lights_state:
    alias: Set toilet lights state
    sequence:
      - choose:
          # IF Motion is detected or the door is open
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.toilet_door
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.toilet_motion
                    state: "on"
            sequence:
              - choose:
                  # IF "Night" scene is active
                  - conditions:
                      - condition: state
                        entity_id: sensor.current_scene
                        state: "Night"
                    sequence:
                      - service: scene.apply
                        data:
                          entities:
                            light.toilet_spot:
                              brightness: 1
                              state: on
                          transition: 0.5

                # ELSE (any other scene is active)
                default:
                  - service: scene.apply
                    data:
                      entities:
                        light.toilet_spot:
                          brightness: 255
                          state: on
                      transition: 0.5

        # ELSE (lights off by default)
        default:
          - service: scene.apply
            data:
              entities:
                light.toilet_spot: off
              transition: 1
