automation:
  - alias: Set light.toilet_spot
    mode: queued
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start

      # Trigger immediately when automations are reloaded
      - platform: event
        event_type: automation_reloaded

      # Trigger immediately when current scene changes to a state we're interested in
      - platform: state
        entity_id: sensor.current_scene
        to: Night

      # Trigger immediately when current scene changes from a state we're interested in
      - platform: state
        entity_id: sensor.current_scene
        from: Night

      # Trigger immediately when the door opens or closes
      - platform: state
        entity_id: binary_sensor.toilet_door
        to:
          - "on"
          - "off"

      # Trigger immediately when motion is detected
      - platform: state
        entity_id: binary_sensor.toilet_motion
        to: "on"

      # Trigger a minute after motion is no longer detected
      - platform: state
        entity_id: binary_sensor.toilet_motion
        to: "off"
        for:
          minutes: 1
    action:
      - service: light.turn_on
        data:
          entity_id: light.toilet_spot
          brightness: >-
            {% set isDoorOpen = is_state('binary_sensor.toilet_door', 'on') %}
            {% set isMotion = is_state('binary_sensor.toilet_motion', 'on') %}
            {% set isNight = is_state('sensor.current_scene', 'Night') %}

            {% if (isDoorOpen or isMotion) and not isNight %}
              255
            {% elif (isDoorOpen or isMotion) and isNight %}
              1
            {% else %}
              0
            {% endif %}
          transition: 0.5
