- alias: Turn on receiver when audio starts playing
  trigger:
    - platform: state
      entity_id: media_player.living_room_speakers
      to: playing
    - platform: state
      entity_id: media_player.upstairs
      to: playing
  condition:
    - condition: state
      entity_id: remote.harmony_hub
      state: "off"
  action:
    - service: remote.turn_on
      data:
        entity_id: remote.harmony_hub
        activity: Listen to Music

- alias: Turn on TV when media starts playing
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      to: playing
  condition:
    - condition: state
      entity_id: remote.harmony_hub
      state: "off"
  action:
    - service: remote.turn_on
      data:
        entity_id: remote.harmony_hub
        activity: Watch Chromecast

- alias: Pause music when turning on the TV
  trigger:
    - platform: template
      value_template: >-
        {%
          if is_state_attr('remote.harmony_hub', 'current_activity', 'Watch TV')
          or
          is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Chromecast')
        %}
          true
        {% endif %}
  action:
    - service: media_player.pause
      data:
        entity_id: media_player.kitchen_speakers
    - service: media_player.pause
      data:
        entity_id: media_player.living_room_speakers
    - service: media_player.pause
      data:
        entity_id: media_player.upstairs
