- alias: Reset speaker volume at 4 AM
  trigger:
    - platform: time
      at: "04:00:00"
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen_speakers
        volume_level: 0.1
    - service: media_player.volume_set
      data:
        entity_id: media_player.living_room_home
        volume_level: 0.3
    - service: media_player.volume_set
      data:
        entity_id: media_player.living_room_speakers
        volume_level: 1
