automation:
  - alias: Temporarily turn off heating when a door or window opens
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_door
        to: "on"
        for:
          seconds: 30
      - platform: state
        entity_id: binary_sensor.living_room_window
        to: "on"
        for:
          seconds: 30
    action:
      - service: script.turn_off_heating

  - alias: Turn heating back on when both door and window are closed
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_door
        from: "on"
        to: "off"
      - platform: state
        entity_id: binary_sensor.living_room_window
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: binary_sensor.kitchen_door
        state: "off"
      - condition: state
        entity_id: binary_sensor.living_room_window
        state: "off"
    action:
      - service: script.turn_on_heating

  - alias: Keep heating off while a door or window is open
    trigger:
      - platform: state
        entity_id: climate.living_room
        from: "off"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.kitchen_door
          state: "on"
        - condition: state
          entity_id: binary_sensor.living_room_window
          state: "on"
    action:
      - service: script.turn_off_heating

script:
  turn_off_heating:
    alias: Turn off heating
    sequence:
      - service: climate.turn_off
        entity_id: climate.living_room
  turn_on_heating:
    alias: Turn on heating
    sequence:
      - service: climate.turn_on
        entity_id: climate.living_room
