sensor:
  - device_class: timestamp
    name: Upcoming alarm
    platform: rest
    resource: !secret living_room_home_alarms_endpoint
    value_template: >-
      {% set alarms = value_json.alarm|sort(attribute='fire_time') %}
      {% if alarms[0] is defined %}
        {{ (alarms[0].fire_time / 1000)|timestamp_local }}
      {% endif %}
