automation:
  - alias: Temporarily turn off heating while backdoor is open
    trigger:
      - platform: state
        entity_id: binary_sensor.backdoor_contact_sensor
        to: "on"
        for:
          seconds: 30
    action:
      - service: script.turn_off_heating

  - alias: Reset scene when door closes
    trigger:
      - platform: state
        entity_id: binary_sensor.backdoor_contact_sensor
        from: "on"
        to: "off"
    action:
      - service: script.scene_selection_reactivate

  - alias: Prevent heating from turning back on while backdoor is open
    trigger:
      - platform: state
        entity_id: climate.living_room
        from: "off"
    condition:
      - condition: state
        entity_id: binary_sensor.backdoor_contact_sensor
        state: "on"
    action:
      - service: script.turn_off_heating

script:
  turn_off_heating:
    alias: Turn off heating
    sequence:
      - service: scene.apply
        data:
          entities:
            climate.living_room: off
