automation:
  - alias: Temporarily turn off heating while backdoor is open
    trigger:
      - platform: state
        entity_id: binary_sensor.backdoor_contact_sensor
        to: "on"
        for:
          seconds: 30
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.living_room
          hvac_mode: "off"
      - wait_template: "{{ is_state('binary_sensor.backdoor_contact_sensor', 'off') }}"
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.living_room
          hvac_mode: "auto"

  - alias: Prevent heating from turning back on while backdoor is open
    trigger:
      - platform: state
        entity_id: climate.living_room
        from: "off"
    condition:
      - condition: state
        entity_id: binary_sensor.backdoor_contact_sensor
        state: "on"
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.living_room
          hvac_mode: "off"
