automation:
  - alias: Media controls through Harmony remote
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          source_name: Home Assistant
          type: keypress
    action:
      - service_template: >-
          {% set scripts = {
            "BackSpace": "media_player.media_stop",
            "Fwd": "media_player.media_next_track",
            "Info": "media_player.media_pause",
            "Play": "media_player.media_play",
            "Rev": "media_player.media_previous_track",
          } %}
          {{ scripts[trigger.event.data.key] }}
        data_template:
          entity_id: >-
            {% set entities = {
              "Watch TV": "",
              "Play a Game": "",
              "Watch a DVD": "",
              "Watch Chromecast": "media_player.living_room_tv",
              "Listen to Music": "media_player.living_room_speakers"
            } %}
            {% set current_activity = state_attr('remote.harmony_hub', 'current_activity') %}
            {{ entities[current_activity] }}