automation:
  - alias: Play CC through Harmony
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          type: keypress
          key: Play
    condition:
      - condition: template
        value_template: "{{ states.remote.harmony_hub.attributes.current_activity == 'Watch Chromecast' }}"
    action:
      - service: media_player.media_play
        entity_id: media_player.tv

  - alias: Pause CC through Harmony
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          type: keypress
          key: Info
    condition:
      - condition: template
        value_template: "{{ states.remote.harmony_hub.attributes.current_activity == 'Watch Chromecast' }}"
    action:
      - service: media_player.media_pause
        entity_id: media_player.tv

  - alias: Play CC Audio through Harmony
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          type: keypress
          key: Play
    condition:
      - condition: template
        value_template: "{{ states.remote.harmony_hub.attributes.current_activity == 'Listen to Music' }}"
    action:
      - service: media_player.media_play
        data_template:
          entity_id: >
            {% if is_state('media_player.upstairs', 'paused') %}
              media_player.upstairs
            {% else %}
              media_player.living_room_speakers
            {% endif %}

  - alias: Pause CC Audio through Harmony
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          type: keypress
          key: Info
    condition:
      - condition: template
        value_template: "{{ states.remote.harmony_hub.attributes.current_activity == 'Listen to Music' }}"
    action:
      - service: media_player.media_pause
        data_template:
          entity_id: >
            {% if is_state('media_player.upstairs', 'playing') %}
              media_player.upstairs
            {% else %}
              media_player.living_room_speakers
            {% endif %}

switch:
  - platform: template
    switches:
      harmony_activity_watch_tv:
        friendly_name: Watch TV
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch TV') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: Watch TV
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub
        icon_template: >-
          {% if is_state_attr('remote.harmony_hub', 'current_activity', 'Watch TV') %}
            mdi:television
          {% else %}
            mdi:television-off
          {% endif %}

      harmony_activity_watch_cc:
        friendly_name: Watch Chromecast
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Chromecast') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: Watch Chromecast
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub
        icon_template: >-
          {% if is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Chromecast') %}
            mdi:cast
          {% else %}
            mdi:cast-off
          {% endif %}

      harmony_activity_listen_music:
        friendly_name: Listen to Music
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Listen to Music') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: Listen to Music
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub
        icon_template: >-
          {% if is_state_attr('remote.harmony_hub', 'current_activity', 'Listen to Music') %}
            mdi:music-note
          {% else %}
            mdi:music-note-off
          {% endif %}

      harmony_activity_play_game:
        friendly_name: Play a Game
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play a Game') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: Play a Game
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub
        icon_template: >-
          {% if is_state_attr('remote.harmony_hub', 'current_activity', 'Play a Game') %}
            mdi:xbox-controller
          {% else %}
            mdi:xbox-controller-off
          {% endif %}
      # harmony_activity_watch_dvd:
      #   friendly_name: Watch a DVD
      #   value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch a DVD') }}"
      #   turn_on:
      #     service: remote.turn_on
      #     data:
      #       entity_id: remote.harmony_hub
      #       activity: Watch a DVD
      #   turn_off:
      #     service: remote.turn_off
      #     data:
      #       entity_id: remote.harmony_hub
