automation:
  - alias: Toggle Kitchen worktop light through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/kitchen_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'right' }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.kitchen_worktop

  - alias: Toggle Kitchen spots through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/kitchen_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'left' }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.kitchen_spots

  - alias: Toggle Living Room pendant through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/living_room_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'left' }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.living_room_pendant

  - alias: Toggle Toilet spot through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/toilet_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click in ['single', 'double'] }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.toilet_spot

  - alias: Toggle Toilet spot through motion sensor
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_occupancy
        to: "on"
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.toilet_spot
          brightness: >-
            {% if is_state('input_select.scene', 'Night') %}
              1
            {% else %}
              255
            {% endif %}
      - wait_template: "{{ is_state('binary_sensor.toilet_occupancy', 'off') }}"
      - condition: and
        conditions:
          - condition: state
            entity_id: light.toilet_spot
            state: "on"
      - service: light.turn_off
        data_template:
          entity_id: light.toilet_spot

light:
  - platform: switch
    name: Kitchen mood lighting
    entity_id: switch.power_outlet_1
  - platform: switch
    name: Living Room pendant
    entity_id: switch.power_outlet_2
  - platform: mqtt
    brightness: true
    command_topic: "zigbee2mqtt/kitchen_spots/set"
    name: Kitchen spots
    schema: json
    state_topic: "zigbee2mqtt/kitchen_spots"
