automation:
  - alias: Update global brightness when settings change
    trigger:
      - platform: state
        entity_id: input_number.morning_brightness
      - platform: state
        entity_id: input_number.day_brightness
      - platform: state
        entity_id: input_number.afternoon_brightness
      - platform: state
        entity_id: input_number.early_evening_brightness
      - platform: state
        entity_id: input_number.evening_brightness
      - platform: state
        entity_id: input_number.night_brightness
    action:
      - service: homeassistant.update_entity
        data:
          entity_id: sensor.global_brightness

  - alias: Toggle Kitchen worktop light through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/kitchen_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'right' }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.kitchen_worktop

  - alias: Toggle Kitchen spots through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/kitchen_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'left' }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.kitchen_spots

  - alias: Toggle Living Room pendant through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/living_room_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'left' }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.living_room_pendant

  - alias: Toggle Toilet spot through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/toilet_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'single' }}"
    action:
      - service: light.toggle
        data_template:
          entity_id: light.toilet_spot
          brightness: 255

  - alias: Toggle Toilet spot through motion sensor
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_occupancy
        to: "on"
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.toilet_spot
          brightness: "{{ states('sensor.global_brightness')|int }}"
      - wait_template: "{{ is_state('binary_sensor.toilet_occupancy', 'off') }}"
      - condition: and
        conditions:
          - condition: state
            entity_id: light.toilet_spot
            state: "on"
      - service: light.turn_off
        data_template:
          entity_id: light.toilet_spot

input_number:
  morning_brightness:
    icon: mdi:tune
    max: 100
    min: 0
    mode: box
    name: Morning brightness
    step: 1
    unit_of_measurement: "%"
  day_brightness:
    icon: mdi:tune
    max: 100
    min: 0
    mode: box
    name: Day brightness
    step: 1
    unit_of_measurement: "%"
  afternoon_brightness:
    icon: mdi:tune
    max: 100
    min: 0
    mode: box
    name: Afternoon brightness
    step: 1
    unit_of_measurement: "%"
  early_evening_brightness:
    icon: mdi:tune
    max: 100
    min: 0
    mode: box
    name: Early evening brightness
    step: 1
    unit_of_measurement: "%"
  evening_brightness:
    icon: mdi:tune
    max: 100
    min: 0
    mode: box
    name: Evening brightness
    step: 1
    unit_of_measurement: "%"
  night_brightness:
    icon: mdi:tune
    max: 100
    min: 0
    mode: box
    name: Night brightness
    step: 1
    unit_of_measurement: "%"

light:
  - platform: switch
    name: Kitchen mood lighting
    entity_id: switch.power_outlet_1
  - platform: switch
    name: Living Room pendant
    entity_id: switch.power_outlet_2
  - platform: mqtt
    brightness: true
    command_topic: "zigbee2mqtt/kitchen_spots/set"
    name: Kitchen spots
    schema: json
    state_topic: "zigbee2mqtt/kitchen_spots"

sensor:
  - platform: template
    sensors:
      global_brightness:
        friendly_name: Brightness
        icon_template: mdi:brightness-6
        value_template: >-
          {% set currentScene = states('input_select.scene')|lower|replace(' ', '_') %}
          {% set settingEntity = "input_number.%s_brightness"|format(currentScene) %}
          {{ ((states(settingEntity)|int / 100) * 255)|int }}
