automation:
  - alias: Toggle Kitchen worktop light through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/kitchen_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'right' }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.kitchen_worktop

  - alias: Toggle Kitchen spots through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/kitchen_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'left' }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.kitchen_spots

  - alias: Toggle Kitchen spots through motion sensor
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        to: "off"
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        to: "on"
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.to_state.state == 'off' }}"
        - condition: numeric_state
          entity_id: sensor.kitchen_illuminance
          below: 10
    action:
      - service_template: "light.turn_{{ trigger.to_state.state }}"
        data:
          entity_id: light.kitchen_spots

  - alias: Turn off Kitchen spots when Day scene is turned on
    trigger:
      - platform: state
        entity_id: input_select.scene
        to: Day
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.kitchen_motion
          state: "off"
    action:
      - service: light.turn_off
        data:
          entity_id: light.kitchen_spots

  - alias: Toggle Living Room pendant through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/living_room_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'left' }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.living_room_pendant

  - alias: Toggle Toilet spot through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/toilet_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click in ['single', 'double'] }}"
    action:
      - service: light.toggle
        data:
          entity_id: light.toilet_spot

  - alias: Toggle Toilet spot through motion sensor
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_occupancy
        to: "off"
      - platform: state
        entity_id: binary_sensor.toilet_occupancy
        to: "on"
    action:
      - service_template: "light.turn_{{ trigger.to_state.state }}"
        data:
          entity_id: light.toilet_spot

  - alias: Fix toilet spot brightness as it turns on
    trigger:
      - platform: state
        entity_id: light.toilet_spot
        to: "on"
    condition:
      - condition: template
        value_template: "{{ not is_state_attr('light.toilet_spot', 'brightness', 1 if is_state('input_select.scene', 'Night') else 255) }}"
    action:
      - service: script.turn_on
        entity_id: script.fix_toilet_spot_brightness

  - alias: Toggle lights when movie changes state
    trigger:
      - entity_id: media_player.living_room_tv
        from: playing
        platform: state
        to: paused
    condition:
      - condition: template
        value_template: "{{ states('input_select.scene') in ['Afternoon', 'Early evening', 'Evening'] }}"
    action:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_spots
      - wait_template: "{{ is_state('media_player.living_room_tv', 'playing') }}"
      - service: light.turn_off
        data:
          entity_id: light.kitchen_spots

group:
  all_lights:
    entities:
      - light.kitchen_mood_lighting
      - light.kitchen_spots
      - light.kitchen_worktop
      - light.living_room_pendant
      - light.toilet_spot
    icon: mdi:lightbulb-outline
    name: Lights
  kitchen_lights:
    entities:
      - light.kitchen_mood_lighting
      - light.kitchen_spots
      - light.kitchen_worktop
    icon: mdi:lightbulb-group-outline
    name: Kitchen lights

light:
  - platform: switch
    name: Kitchen mood lighting
    entity_id: switch.power_outlet_1
  - platform: switch
    name: Living Room pendant
    entity_id: switch.power_outlet_2
  - platform: mqtt
    brightness: true
    command_topic: "zigbee2mqtt/kitchen_spots/set"
    name: Kitchen spots
    schema: json
    state_topic: "zigbee2mqtt/kitchen_spots"

script:
  fix_toilet_spot_brightness:
    alias: Fix toilet spot brightness
    sequence:
      - condition: template
        value_template: "{{ not is_state_attr('light.toilet_spot', 'brightness', 1 if is_state('input_select.scene', 'Night') else 255) }}"
      - service: light.turn_on
        data_template:
          entity_id: light.toilet_spot
          brightness: "{{ 1 if is_state('input_select.scene', 'Night') else 255 }}"
          transition: 1
