automation:
  - alias: Toggle Kitchen worktop light
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/kitchen_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'right' }}"
    action:
      - data:
          entity_id: light.kitchen_worktop
        service: light.toggle

  - alias: Toggle Living Room pendant
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/living_room_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'left' }}"
    action:
      - data:
          entity_id: light.living_room_pendant
        service: light.toggle

light:
  - platform: switch
    name: Kitchen mood lighting
    entity_id: switch.power_outlet_1
  - platform: switch
    name: Living Room pendant
    entity_id: switch.power_outlet_2
