automation:
  - alias: Reset speaker volume at 4 AM
    trigger:
      - platform: time
        at: "04:00:00"
    action:
      - service: script.turn_on
        entity_id: script.reset_volume

  - alias: Turn on receiver when audio starts playing
    trigger:
      - platform: state
        entity_id: media_player.living_room_speakers
        to: playing
      # No need to include other media players (such as groups), because once they start playing
      # the only speaker that matters, living_room_speakers, also starts playing.
    condition:
      - condition: state
        entity_id: remote.harmony_hub
        state: "off"
    action:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Listen to Music

  - alias: Turn on TV when media starts playing
    trigger:
      - platform: state
        entity_id: media_player.living_room_tv
        to: playing
    condition:
      - condition: state
        entity_id: remote.harmony_hub
        state: "off"
    action:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Watch Chromecast

  - alias: Pause music when turning on the TV
    trigger:
      - platform: template
        value_template: "{{ state_attr('remote.harmony_hub', 'current_activity') in ['Watch TV', 'Watch Chromecast', 'Play a Game'] }}"
    action:
      - service: media_player.media_pause
        data:
          entity_id: media_player.kitchen_speakers
      - service: media_player.media_pause
        data:
          entity_id: media_player.living_room_speakers
      - service: media_player.media_pause
        data:
          entity_id: media_player.upstairs

  - alias: Media controls through Harmony remote
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          source_name: Home Assistant
          type: keypress
    action:
      - service_template: >-
          {% set scripts = {
            "BackSpace": "media_player.media_stop",
            "Pause": "media_player.media_pause",
            "Info": "media_player.media_play",
          } %}
          {{ scripts[trigger.event.data.key] }}
        data_template:
          entity_id: "{{ 'media_player.living_room_tv' if state_attr('remote.harmony_hub', 'current_activity') in ['Watch Chromecast'] else 'media_player.living_room_speakers' }}"

  - alias: Sync activity to Harmony Hub's current activity
    trigger:
      - platform: state
        entity_id: remote.harmony_hub
    action:
      - service: script.turn_on
        entity_id: script.activity_sync

  - alias: Sync to Harmony Hub's current activity to activity
    trigger:
      - platform: state
        entity_id: input_select.activity
    action:
      - service_template: >-
          {% if trigger.to_state.state == "Off" %}
            remote.turn_off
          {% else %}
            remote.turn_on
          {% endif %}
        data_template:
          entity_id: remote.harmony_hub
          activity: >-
            {% if trigger.to_state.state == "Off" %}
              null
            {% else %}
              {{ trigger.to_state.state }}
            {% endif %}

  - alias: Sync subwoofer power state to receiver power state through Harmony activity
    trigger:
      - platform: state
        entity_id: remote.harmony_hub
    action:
      - service_template: >-
          {% if trigger.to_state.state == 'on' %}
            switch.turn_on
          {% else %}
            switch.turn_off
          {% endif %}
        entity_id: switch.power_outlet_3

input_select:
  activity:
    icon: mdi:pulse
    name: Activity
    options:
      - Watch TV
      - Play a Game
      - Watch a DVD
      - Listen to Music
      - Watch Chromecast
      - "Off"

script:
  activity_sync:
    alias: Sync activity to Harmony Hub's current activity
    sequence:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.activity
          option: >-
            {% if state_attr('remote.harmony_hub', 'current_activity') == "PowerOff" %}
              Off
            {% else %}
              {{ state_attr('remote.harmony_hub', 'current_activity') }}
            {% endif %}

  reset_volume:
    alias: Reset speaker volumes
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.downstairs_speaker
          volume_level: 0.4
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen_speakers
          volume_level: 0.1
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_home
          volume_level: 0.3
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_speakers
          volume_level: 1
