automation:
  - alias: Reset speaker volume at 4 AM
    trigger:
      - platform: time
        at: "04:00:00"
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen_speakers
          volume_level: 0.1
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_home
          volume_level: 0.3
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_speakers
          volume_level:

  - alias: Turn on receiver when audio starts playing
    trigger:
      - platform: state
        entity_id: media_player.living_room_speakers
        to: playing
      - platform: state
        entity_id: media_player.upstairs
        to: playing
    condition:
      - condition: state
        entity_id: remote.harmony_hub
        state: "off"
    action:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Listen to Music

  - alias: Turn on TV when media starts playing
    trigger:
      - platform: state
        entity_id: media_player.living_room_tv
        to: playing
    condition:
      - condition: state
        entity_id: remote.harmony_hub
        state: "off"
    action:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Watch Chromecast

  - alias: Pause music when turning on the TV
    trigger:
      - platform: template
        value_template: "{{ state_attr('remote.harmony_hub', 'current_activity') in ['Watch TV', 'Watch Chromecast', 'Play a Game'] }}"
    action:
      - service: media_player.media_pause
        data:
          entity_id: media_player.kitchen_speakers
      - service: media_player.media_pause
        data:
          entity_id: media_player.living_room_speakers
      - service: media_player.media_pause
        data:
          entity_id: media_player.upstairs

  - alias: Play media through Harmony remote
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          source_name: Home Assistant
          type: keypress
          key: Play
    condition:
      - condition: template
        value_template: "{{ state_attr('remote.harmony_hub', 'current_activity') in ['Watch TV', 'Watch Chromecast'] }}"
    action:
      - service: media_player.media_play
        data:
          entity_id: media_player.living_room_tv

  - alias: Pause media through Harmony remote
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          source_name: Home Assistant
          type: keypress
          key: Info # Using "Info" because Emulated Roku does not support the "Pause" command
    condition:
      - condition: template
        value_template: "{{ state_attr('remote.harmony_hub', 'current_activity') in ['Watch TV', 'Watch Chromecast'] }}"
    action:
      - service: media_player.media_pause
        data:
          entity_id: media_player.living_room_tv

  - alias: Play music through Harmony remote
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          source_name: Home Assistant
          type: keypress
          key: Play
    condition:
      - condition: template
        value_template: "{{ state_attr('remote.harmony_hub', 'current_activity') in ['Listen to Music'] }}"
    action:
      - service: media_player.media_play
        data_template:
          entity_id: "{{ states.media_player | selectattr('entity_id', 'in', ['media_player.kitchen_speakers', 'media_player.living_room_speakers', 'media_player.upstairs']) | selectattr('state', 'eq', 'paused') | map(attribute='entity_id') | join(',') }}"

  - alias: Pause music through Harmony remote
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          source_name: Home Assistant
          type: keypress
          key: Info # Using "Info" because Emulated Roku does not support the "Pause" command
    condition:
      - condition: template
        value_template: "{{ state_attr('remote.harmony_hub', 'current_activity') in ['Listen to Music'] }}"
    action:
      - service: media_player.media_pause
        data_template:
          entity_id: "{{ states.media_player | selectattr('entity_id', 'in', ['media_player.kitchen_speakers', 'media_player.living_room_speakers', 'media_player.upstairs']) | selectattr('state', 'eq', 'playing') | map(attribute='entity_id') | join(',') }}"

  - alias: Sync activity to Harmony Hub's current activity
    trigger:
      - platform: state
        entity_id: remote.harmony_hub
    action:
      - service: script.turn_on
        entity_id: script.activity_sync

  - alias: Sync to Harmony Hub's current activity to activity
    trigger:
      - platform: state
        entity_id: input_select.activity
    action:
      - service_template: >-
          {% if trigger.to_state.state == "Off" %}
            remote.turn_off
          {% else %}
            remote.turn_on
          {% endif %}
        data_template:
          entity_id: remote.harmony_hub
          activity: >-
            {% if trigger.to_state.state == "Off" %}
              null
            {% else %}
              {{ trigger.to_state.state }}
            {% endif %}

input_select:
  activity:
    icon: mdi:pulse
    name: Activity
    options:
      - Watch TV
      - Play a Game
      - Watch a DVD
      - Listen to Music
      - Watch Chromecast
      - "Off"

script:
  activity_sync:
    alias: Sync activity to Harmony Hub's current activity
    sequence:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.activity
          option: >-
            {% if state_attr('remote.harmony_hub', 'current_activity') == "PowerOff" %}
              Off
            {% else %}
              {{ state_attr('remote.harmony_hub', 'current_activity') }}
            {% endif %}
