automation:
  - alias: Reset speaker volume at 4 AM
    trigger:
      - platform: time
        at: "04:00:00"
    action:
      - service: script.reset_volume

group:
  all_media_players:
    entities:
      - media_player.downstairs_speaker
      - media_player.everywhere
      - media_player.kitchen_speakers
      - media_player.living_room_home_mini
      - media_player.living_room_speakers
      - media_player.living_room_tv
      - media_player.upstairs
    icon: mdi:play-box-outline
    name: Media

media_player:
  - platform: nadtcp2
    name: Amplifier
    host: !secret nad_amplifier_ip

script:
  reset_volume:
    alias: Reset speaker volumes
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.downstairs_speaker
          volume_level: 0.4
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen_speakers
          volume_level: 0.1
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_home_mini
          volume_level: 0.35
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_speakers
          volume_level: 0.42857142857142855
