automation:
  - alias: Reset speaker volume at 4 AM
    trigger:
      - platform: time
        at: "04:00:00"
    action:
      - service: script.reset_volume

  - alias: Pause music when turning on the TV
    trigger:
      - platform: template
        value_template: "{{ state_attr('remote.harmony_hub', 'current_activity') in ['Watch TV', 'Watch Chromecast', 'Play a Game'] }}"
    action:
      - service: media_player.media_pause
        data:
          entity_id: media_player.kitchen_speakers
      - service: media_player.media_pause
        data:
          entity_id: media_player.living_room_speakers
      - service: media_player.media_pause
        data:
          entity_id: media_player.upstairs

group:
  all_media_players:
    entities:
      - media_player.downstairs_speaker
      - media_player.everywhere
      - media_player.kitchen_speakers
      - media_player.living_room_home_mini
      - media_player.living_room_speakers
      - media_player.living_room_tv
      - media_player.upstairs
    icon: mdi:play-box-outline
    name: Media

media_player:
  # - platform: ziggo_mediabox_xl
  #   host: !secret ziggo_mediabox_xl_host
  #   name: Mediabox XL
  - platform: xboxone
    device: !secret xbox_one_device_id
    name: Xbox

script:
  reset_volume:
    alias: Reset speaker volumes
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.downstairs_speaker
          volume_level: 0.4
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen_speakers
          volume_level: 0.1
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_home_mini
          volume_level: 0.35
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_speakers
          volume_level: 1
