group:
  everyone:
    entities:
      - person.niels
      - person.laura
    icon: mdi:account-group-outline
    name: People

homeassistant:
  customize:
    person.laura:
      entity_picture: /local/images/laura.jpg
    person.niels:
      entity_picture: /local/images/niels.jpg

input_boolean:
  guest_mode:
    icon: mdi:bed-outline
    name: Guest mode

notify:
  - name: all_devices
    platform: group
    services:
      # - service: mobile_app_pixel_3a
      - service: mobile_app_pixel_4

person:
