group:
  everyone:
    entities:
      - person.niels
      - person.laura
    icon: mdi:account-group-outline
    name: People

homeassistant:
  customize:
    person.laura:
      entity_picture: /local/images/laura.jpg
    person.niels:
      entity_picture: /local/images/niels.jpg

person:
