device_tracker:
  - platform: bluetooth_tracker
    request_rssi: true
    new_device_defaults:
      track_new_devices: false

group:
  everyone:
    entities:
      - person.niels
      - person.laura
    icon: mdi:account-group-outline
    name: People

input_select:
  presence:
    icon: mdi:home-circle
    name: Presence
    options:
      - Home
      - Away
      - Vacation

sensor:
  - platform: google_wifi
    host: !secret default_gateway_ip
