device_tracker:
  - platform: bluetooth_tracker
    request_rssi: true
    new_device_defaults:
      hide_if_away: false
      track_new_devices: false
  - platform: upc_connect
    host: !secret default_gateway_ip
    new_device_defaults:
      hide_if_away: false
      track_new_devices: false

group:
  everyone:
    entities:
      - person.niels
      - person.laura
    icon: mdi:account-group
    name: Everyone
  george:
    entities:
      - sensor.george_home
    icon: mdi:cat
    name: George

input_boolean:
  george_home_toggle:
    name: George
    initial: on
    icon: mdi:cat

sensor:
  - platform: template
    sensors:
      george_home:
        friendly_name: George
        icon_template: mdi:cat
        value_template: >-
          {% if is_state('input_boolean.george_home_toggle', 'on') %}
            home
          {% else %}
            not_home
          {% endif %}
