automation:
  - alias: Set home mode to Home
    trigger:
      - platform: state
        entity_id: group.everyone
        to: home
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.home

  - alias: Set home mode to Away
    trigger:
      - platform: state
        entity_id: group.everyone
        to: not_home
        for:
          minutes: 15
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.away

  - alias: Set home mode to Vacation
    trigger:
      - platform: state
        entity_id: group.everyone
        to: not_home
        for:
          hours: 24
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.vacation

device_tracker:
  - platform: bluetooth_tracker
    request_rssi: true
    new_device_defaults:
      hide_if_away: false
      track_new_devices: false

group:
  everyone:
    entities:
      - person.niels
      - person.laura
    icon: mdi:account-group
    name: Everyone
  george:
    entities:
      - sensor.george_home
    icon: mdi:cat
    name: George

input_boolean:
  george_home_toggle:
    name: George
    initial: on
    icon: mdi:cat

input_select:
  presence:
    icon: mdi:home-circle
    name: Presence
    options:
      - Home
      - Away
      - Vacation

sensor:
  - platform: google_wifi
    host: !secret default_gateway_ip
  - platform: template
    sensors:
      george_home:
        friendly_name: George
        icon_template: mdi:cat
        value_template: >-
          {% if is_state('input_boolean.george_home_toggle', 'on') %}
            home
          {% else %}
            not_home
          {% endif %}
