# Pet
input_boolean:
  george_home_toggle:
    name: George
    initial: on
    icon: mdi:cat

sensor:
  - platform: template
    sensors:
      george_home:
        friendly_name: George
        icon_template: mdi:cat
        value_template: >-
          {% if is_state('input_boolean.george_home_toggle', 'on') %}
            home
          {% else %}
            not_home
          {% endif %}

# Humans
device_tracker:
  - platform: bluetooth_tracker
    request_rssi: true
    new_device_defaults:
      hide_if_away: false
      track_new_devices: false
  - platform: upc_connect
    host: !secret default_gateway_ip
    new_device_defaults:
      hide_if_away: false
      track_new_devices: false

group:
  pixel_2_xl:
    entities:
      - device_tracker.pixel_2_xl_bt
      - device_tracker.pixel_2_xl_wifi
    icon: mdi:cellphone
    name: Niels' Pixel 2 XL
  galaxy_a5:
    entities:
      - device_tracker.galaxy_a5_bt
      - device_tracker.galaxy_a5_wifi
    icon: mdi:cellphone
    name: Laura's Galaxy A5
  everyone:
    entities:
      - group.niels
      - group.laura
    icon: mdi:account-group
    name: Everyone
  george:
    entities:
      - sensor.george_home
    icon: mdi:cat
    name: George
  laura:
    entities:
      - group.galaxy_a5
    icon: mdi:account
    name: Laura
  niels:
    entities:
      - group.pixel_2_xl
    icon: mdi:account
    name: Niels
