device_tracker:
  - platform: bluetooth_tracker
    request_rssi: true
    new_device_defaults:
      track_new_devices: false

group:
  everyone:
    entities:
      - person.niels
      - person.laura
    icon: mdi:account-group-outline
    name: People
  george:
    entities:
      - sensor.george_home
    icon: mdi:cat
    name: George

input_boolean:
  george_home_toggle:
    name: George
    initial: on
    icon: mdi:cat

input_select:
  presence:
    icon: mdi:home-circle
    name: Presence
    options:
      - Home
      - Away
      - Vacation

sensor:
  - platform: google_wifi
    host: !secret default_gateway_ip
  - platform: template
    sensors:
      george_home:
        friendly_name: George
        icon_template: mdi:cat
        value_template: >-
          {% if is_state('input_boolean.george_home_toggle', 'on') %}
            home
          {% else %}
            not_home
          {% endif %}
