automation:
  - alias: Media controls through Harmony remote
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          source_name: Home Assistant
          type: keypress
    condition:
      - condition: template
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Chromecast') }}"
    action:
      - service_template: >-
          {% set services = {
            "BackSpace": "media_player.media_stop",
            "Down": "media_player.volume_down",
            "Fwd": "media_player.media_next_track",
            "Home": "media_player.volume_mute",
            "Info": "media_player.media_pause",
            "Play": "media_player.media_play",
            "Rev": "media_player.media_previous_track",
            "Up": "media_player.volume_up",
          } %}
          {{ services[trigger.event.data.key] }}
        data:
          entity_id: media_player.living_room_tv

  - alias: Set correct input on amplifier based on Harmony activity
    trigger:
      - platform: state
        entity_id: remote.harmony_hub
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'off' }}"
    action:
      - delay:
          seconds: "{{ 6 if trigger.from_state.state == 'off' else 0 }}"
      - service: script.input_sync

  - alias: Sync subwoofer power to amplifier power
    trigger:
      - platform: state
        entity_id: media_player.amplifier
        to: "on"
      - platform: state
        entity_id: media_player.amplifier
        to: "off"
    action:
      - service_template: "switch.turn_{{ trigger.to_state.state }}"
        data:
          entity_id: switch.power_outlet_3

  - alias: Turn on Harmony activity based on amplifier input change
    trigger:
      - platform: state
        entity_id: media_player.amplifier
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.attributes.source != 'Wireless' and trigger.to_state.attributes.source == 'Wireless' }}"
    action:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Listen to Music

script:
  input_sync:
    alias: Set correct input on amplifier based on Harmony activity
    sequence:
      - condition: state
        entity_id: remote.harmony_hub
        state: 'on'
      - service: media_player.select_source
        data_template:
          entity_id: media_player.amplifier
          source: >-
            {% if is_state_attr('remote.harmony_hub', 'current_activity', 'Listen to Music') %}
              Wireless
            {% elif is_state_attr('remote.harmony_hub', 'current_activity', 'Listen to Vinyl') %}
              Phono
            {% else %}
              Opt2
            {% endif %}

switch:
  - platform: template
    switches:
      remote_tv:
        friendly_name: TV
        icon_template: mdi:remote
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch TV') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: Watch TV
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub
      remote_xbox:
        friendly_name: Game
        icon_template: mdi:remote
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play a Game') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: Play a Game
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub
      remote_music:
        friendly_name: Speakers
        icon_template: mdi:remote
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Listen to Music') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: Listen to Music
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub
      remote_vinyl:
        friendly_name: Vinyl
        icon_template: mdi:remote
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Listen to Vinyl') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: Listen to Vinyl
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub
      remote_chromecast:
        friendly_name: Chromecast
        icon_template: mdi:remote
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Chromecast') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: Watch Chromecast
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub