automation:
  - alias: Sync activity scene to Harmony activity
    trigger:
      - platform: state
        entity_id: remote.harmony_hub
    action:
      - service: script.activity_sync

scene:
  - name: Listen to Music
    entities:
      # media_player.mediabox: off
      # media_player.receiver: on
      # media_player.tv: off
      media_player.xbox: off
      switch.power_outlet_3: on

  - name: Watch TV
    entities:
      # media_player.mediabox: on
      # media_player.receiver: on
      # media_player.tv: on
      media_player.xbox: off
      switch.power_outlet_3: on

  - name: Watch Chromecast
    entities:
      # media_player.mediabox: off
      # media_player.receiver: on
      # media_player.tv: on
      media_player.xbox: off
      switch.power_outlet_3: on

  - name: Play a Game
    entities:
      # media_player.mediabox: off
      # media_player.receiver: on
      # media_player.tv: on
      media_player.xbox: on
      switch.power_outlet_3: on

  - name: poweroff
    entities:
      # media_player.mediabox: off
      # media_player.receiver: off
      # media_player.tv: off
      media_player.xbox: off
      switch.power_outlet_3: off

script:
  activity_sync:
    alias: Sync activity scene to Harmony activity
    sequence:
      - service: scene.turn_on
        data_template:
          entity_id: scene.{{ state_attr('remote.harmony_hub', 'current_activity') | lower | replace(' ', '_') }}

switch:
  - platform: template
    switches:
      remote_tv:
        friendly_name: TV
        icon_template: mdi:remote
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch TV') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: Watch TV
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub
      remote_xbox:
        friendly_name: Xbox
        icon_template: mdi:remote
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play a Game') or is_state_attr('remote.harmony_hub', 'current_activity', 'Watch a DVD') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: Play a Game
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub
      remote_receiver:
        friendly_name: Receiver
        icon_template: mdi:remote
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Listen to Music') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: Listen to Music
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub
      remote_chromecast:
        friendly_name: Chromecast
        icon_template: mdi:remote
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Chromecast') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: Watch Chromecast
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub