binary_sensor:
  - platform: template
    sensors:
      tv_on:
        friendly_name: TV is on
        value_template: >-
          {{ state_attr('remote.harmony_hub', 'current_activity') in ['Watch TV', 'Watch Chromecast', 'Play a Game'] }}

sensor:
  - platform: history_stats
    name: Time Niels spent at home the past 7 days
    entity_id: group.niels
    state: home
    type: ratio
    start: "{{ as_timestamp(now()) - 7 * 24 * 60 * 60 }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Time Laura spent at home the past 7 days
    entity_id: group.laura
    state: home
    type: ratio
    start: "{{ as_timestamp(now()) - 7 * 24 * 60 * 60 }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Time spent watching TV
    entity_id: binary_sensor.tv_on
    state: "on"
    type: time
    start: "{{ as_timestamp(now()) - 7 * 24 * 60 * 60 }}"
    end: "{{ now() }}"
