input_number:
  morning_threshold:
    icon: mdi:tune
    min: -10
    max: 10
    name: Morning threshold
    step: 0.5
  day_threshold:
    icon: mdi:tune
    min: -10
    max: 10
    name: Day threshold
    step: 0.5
  afternoon_threshold:
    icon: mdi:tune
    min: -10
    max: 10
    name: Afternoon threshold
    step: 0.5
  dusk_threshold:
    icon: mdi:tune
    min: -10
    max: 10
    name: Dusk threshold
    step: 0.5
  evening_threshold:
    icon: mdi:tune
    min: -10
    max: 10
    name: Evening threshold
    step: 0.5

sensor:
  - platform: template
    sensors:
      sun_direction:
        friendly_name: Sun direction
        value_template: >-
          {% if as_timestamp(state_attr('sun.sun', 'next_noon')) - as_timestamp(state_attr('sun.sun', 'next_midnight')) < 0 %}
            rising
          {% else %}
            setting
          {% endif %}
        icon_template: >-
          {% if as_timestamp(state_attr('sun.sun', 'next_noon')) - as_timestamp(state_attr('sun.sun', 'next_midnight')) < 0 %}
            mdi:weather-sunset-up
          {% else %}
            mdi:weather-sunset-down
          {% endif %}
      time_of_day:
        friendly_name: Time of day
        value_template: >-
          {% if is_state('sensor.sun_direction', 'rising') and state_attr('sun.sun', 'elevation') > states('input_number.day_threshold')|float %}
            Day
          {% elif is_state('sensor.sun_direction', 'rising') and state_attr('sun.sun', 'elevation') > states('input_number.morning_threshold')|float %}
            Morning
          {% elif is_state('sensor.sun_direction', 'rising') %}
            Night
          {% elif is_state('sensor.sun_direction', 'setting') and state_attr('sun.sun', 'elevation') < states('input_number.evening_threshold')|float %}
            Evening
          {% elif is_state('sensor.sun_direction', 'setting') and state_attr('sun.sun', 'elevation') < states('input_number.dusk_threshold')|float %}
            Dusk
          {% elif is_state('sensor.sun_direction', 'setting') and state_attr('sun.sun', 'elevation') < states('input_number.afternoon_threshold')|float %}
            Afternoon
          {% else %}
            Day
          {% endif %}
        icon_template: mdi:calendar-clock

script:
  scene_sync:
    alias: Scene sync
    sequence:
      - service: scene.turn_on
        data_template:
          entity_id: scene.{{ states('input_select.primary_scene') | lower | replace(' ', '_') }}

input_select:
  presence:
    icon: mdi:home-circle
    name: Presence
    options:
      - Home
      - Away
      - Vacation
  primary_scene:
    icon: mdi:theme-light-dark
    name: Scene
    options:
      - Morning
      - Day
      - Afternoon
      - Dusk
      - Evening
      - Night
      - Away
      - Vacation
  secondary_scene:
    name: Activity
    options:
      - None
      - Cooking
      - Movie

scene:
  - name: Home
    entities:
      input_select.presence:
        option: Home
      automation.set_home_mode_to_home: off
      automation.set_home_mode_to_away: on
      automation.set_home_mode_to_vacation: on
      automation.pause_media_through_harmony_remote: on
      automation.pause_music_through_harmony_remote: on
      automation.pause_music_when_turning_on_the_tv: on
      automation.play_media_through_harmony_remote: on
      automation.play_music_through_harmony_remote: on
      automation.trigger_morning_scene_at_fixed_time: on
      automation.trigger_night_scene_at_fixed_time: on
      automation.turn_on_receiver_when_audio_starts_playing: on
      automation.turn_on_tv_when_media_starts_playing: on
      automation.turn_on_toilet_light: on

  - name: Away
    entities:
      input_select.presence:
        option: Away
      input_select.primary_scene:
        option: Away
      input_select.secondary_scene:
        option: None
      automation.set_home_mode_to_home: on
      automation.set_home_mode_to_away: off
      automation.set_home_mode_to_vacation: on
      automation.pause_media_through_harmony_remote: off
      automation.pause_music_through_harmony_remote: off
      automation.pause_music_when_turning_on_the_tv: off
      automation.play_media_through_harmony_remote: off
      automation.play_music_through_harmony_remote: off
      automation.trigger_morning_scene_at_fixed_time: off
      automation.trigger_night_scene_at_fixed_time: off
      automation.turn_on_receiver_when_audio_starts_playing: off
      automation.turn_on_tv_when_media_starts_playing: off
      climate.living_room:
        temperature: 16
      light.kitchen_mood_lighting: off
      light.kitchen_worktop: off
      light.living_room_pendant: off
      media_player.kitchen_speakers: off
      media_player.living_room_tv: off
      media_player.upstairs: off
      remote.harmony_hub: off

  - name: Vacation
    entities:
      input_select.presence:
        option: Vacation
      input_select.primary_scene:
        option: Vacation
      input_select.secondary_scene:
        option: None
      automation.set_home_mode_to_home: on
      automation.set_home_mode_to_away: off
      automation.set_home_mode_to_vacation: off
      automation.pause_media_through_harmony_remote: off
      automation.pause_music_through_harmony_remote: off
      automation.pause_music_when_turning_on_the_tv: off
      automation.play_media_through_harmony_remote: off
      automation.play_music_through_harmony_remote: off
      automation.trigger_morning_scene_at_fixed_time: off
      automation.trigger_night_scene_at_fixed_time: off
      automation.turn_on_receiver_when_audio_starts_playing: off
      automation.turn_on_tv_when_media_starts_playing: off
      climate.living_room:
        temperature: 16
      light.kitchen_mood_lighting: off
      light.kitchen_worktop: off
      light.living_room_pendant: off
      media_player.kitchen_speakers: off
      media_player.living_room_tv: off
      media_player.upstairs: off
      remote.harmony_hub: off

  - name: Morning
    entities:
      input_select.presence:
        option: Home
      input_select.primary_scene:
        option: Morning
      climate.living_room:
        temperature: 19
      light.kitchen_mood_lighting: off
      light.living_room_pendant: on

  - name: Day
    entities:
      input_select.presence:
        option: Home
      input_select.primary_scene:
        option: Day
      climate.living_room:
        temperature: 19
      light.kitchen_mood_lighting: off
      light.living_room_pendant: off

  - name: Afternoon
    entities:
      input_select.presence:
        option: Home
      input_select.primary_scene:
        option: Afternoon
      climate.living_room:
        temperature: 20
      light.kitchen_mood_lighting: on
      light.living_room_pendant: on

  - name: Dusk
    entities:
      input_select.presence:
        option: Home
      input_select.primary_scene:
        option: Dusk
      climate.living_room:
        temperature: 20
      light.kitchen_mood_lighting: on
      light.living_room_pendant: on

  - name: Evening
    entities:
      input_select.presence:
        option: Home
      input_select.primary_scene:
        option: Evening
      climate.living_room:
        temperature: 20
      light.kitchen_mood_lighting: on
      light.living_room_pendant: on

  - name: Night
    entities:
      input_select.presence:
        option: Home
      input_select.primary_scene:
        option: Night
      climate.living_room:
        temperature: 16
      light.kitchen_mood_lighting: off
      light.kitchen_worktop: off
      light.living_room_pendant: off

  - name: Cooking
    entities:
      input_select.presence:
        option: Home
      input_select.secondary_scene:
        option: Cooking
      light.kitchen_worktop: on

  - name: Movie
    entities:
      input_select.presence:
        option: Home
      input_select.secondary_scene:
        option: Movie
