automation:
  - alias: Set home mode to Home
    trigger:
      - platform: state
        entity_id: group.everyone
        to: home
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.home
      - service_template: "{{ 'script' if not is_state('sensor.time_of_day', 'Night') else 'scene'}}.turn_on"
        data_template:
          entity_id: >-
            {% if is_state('sensor.time_of_day', 'Night') %}
              scene.{{ 'morning' if is_state('sensor.sun_direction', 'Rising') else 'evening' }}
            {% else %}
              script.scene_sync
            {% endif %}

  - alias: Set home mode to Away
    trigger:
      - platform: state
        entity_id: group.everyone
        to: not_home
        for:
          minutes: 15
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.away

  - alias: Set home mode to Vacation
    trigger:
      - platform: state
        entity_id: group.everyone
        to: not_home
        for:
          hours: 24
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.vacation

  - alias: Turn off Night scene
    trigger:
      - platform: time
        at: 06:30:00
      - platform: time
        at: 08:30:00
    condition:
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: time
                after: 06:30:00
              - condition: state
                entity_id: binary_sensor.workday_sensor
                state: "on"
          - condition: and
            conditions:
              - condition: time
                after: 08:30:00
              - condition: state
                entity_id: binary_sensor.workday_sensor
                state: "off"
    action:
      - service_template: "{{ 'scene' if is_state('input_select.scene', 'Night') else 'script' }}.turn_on"
        data_template:
          entity_id: "{{ 'scene.morning' if is_state('input_select.scene', 'Night') else 'script.scene_sync' }}"

  - alias: Handle scene override
    trigger:
      - platform: state
        entity_id: input_select.presence
      - platform: state
        entity_id: input_select.scene
    action:
      - service: scene.turn_on
        data_template:
          entity_id: "scene.{{ trigger.to_state.state | lower | replace(' ', '_') }}"

  - alias: Toggle Cooking scene through wall button press
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/kitchen_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'right' }}"
    action:
      - service: scene.turn_on
        data_template:
          entity_id: "scene.{{ 'cooking' if not is_state('input_select.scene', 'Cooking') else 'eating' }}"

  - alias: Turn off Eating scene after 30 minutes
    trigger:
      - platform: state
        entity_id: input_select.scene
        to: Eating
        for: 00:30:00
    action:
      - service: script.turn_on
        data:
          entity_id: script.scene_sync

binary_sensor:
  - platform: workday
    country: NL

group:
  all_scenes:
    entities:
      - scene.morning
      - scene.day
      - scene.afternoon
      - scene.early_evening
      - scene.evening
      - scene.night
    icon: mdi:theme-light-dark
    name: Scenes

input_select:
  scene:
    icon: mdi:theme-light-dark
    name: Scene
    options:
      - Morning
      - Day
      - Afternoon
      - Early evening
      - Evening
      - Night
      - Away
      - Vacation
      - Cooking
      - Eating

scene:
  - name: Home
    entities:
      input_select.presence: Home

  - name: Away
    entities:
      input_select.presence: Away
      input_select.scene: Away
      automation.synchronise_scene_to_time_of_day: off
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 16
      light.kitchen_mood_lighting: off
      light.kitchen_spots: off
      light.kitchen_worktop: off
      light.living_room_pendant: off
      light.living_room_spots: off
      light.toilet_spot: off
      remote.harmony_hub: off

  - name: Vacation
    entities:
      input_select.presence: Vacation
      input_select.scene: Vacation
      automation.synchronise_scene_to_time_of_day: off
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 16
      light.kitchen_mood_lighting: off
      light.kitchen_spots: off
      light.kitchen_worktop: off
      light.living_room_pendant: off
      light.living_room_spots: off
      light.toilet_spot: off
      remote.harmony_hub: off

  - name: Morning
    entities:
      input_select.presence: Home
      input_select.scene: Morning
      automation.synchronise_scene_to_time_of_day: on
      automation.toggle_kitchen_spots_through_motion_sensor: off
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 19
      light.kitchen_mood_lighting: off
      light.kitchen_spots: on
      light.kitchen_worktop: off
      light.living_room_pendant: on
      light.living_room_spots: off

  - name: Day
    entities:
      input_select.presence: Home
      input_select.scene: Day
      automation.synchronise_scene_to_time_of_day: on
      automation.toggle_kitchen_spots_through_motion_sensor: on
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 19
      light.kitchen_mood_lighting: off
      light.kitchen_worktop: off
      light.living_room_pendant: off
      light.living_room_spots: off

  - name: Afternoon
    entities:
      input_select.presence: Home
      input_select.scene: Afternoon
      automation.synchronise_scene_to_time_of_day: on
      automation.toggle_kitchen_spots_through_motion_sensor: on
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 19
      light.kitchen_mood_lighting: on
      light.kitchen_worktop: off
      light.living_room_pendant: on
      light.living_room_spots: off

  - name: Early evening
    entities:
      input_select.presence: Home
      input_select.scene: Early evening
      automation.synchronise_scene_to_time_of_day: on
      automation.toggle_kitchen_spots_through_motion_sensor: on
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 19
      light.kitchen_mood_lighting: on
      light.kitchen_worktop: off
      light.living_room_pendant: on
      light.living_room_spots:
        brightness: 65
        color_temp: 475
        state: on
        transition: 1

  - name: Evening
    entities:
      input_select.presence: Home
      input_select.scene: Evening
      automation.synchronise_scene_to_time_of_day: on
      automation.toggle_kitchen_spots_through_motion_sensor: on
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 19
      light.kitchen_mood_lighting: on
      light.kitchen_worktop: off
      light.living_room_pendant: on
      light.living_room_spots:
        brightness: 65
        color_temp: 475
        state: on
        transition: 1

  - name: Night
    entities:
      input_select.presence: Home
      input_select.scene: Night
      automation.synchronise_scene_to_time_of_day: off
      automation.toggle_kitchen_spots_through_motion_sensor: on
      automation.turn_off_night_scene: on
      climate.living_room:
        state: heat
        temperature: 16
      light.kitchen_mood_lighting: off
      light.kitchen_spots: off
      light.kitchen_worktop: off
      light.living_room_pendant: off
      light.living_room_spots: off
      remote.harmony_hub: off

  - name: Cooking
    entities:
      input_select.presence: Home
      input_select.scene: Cooking
      automation.synchronise_scene_to_time_of_day: off
      automation.toggle_kitchen_spots_through_motion_sensor: off
      light.kitchen_worktop: on
      light.kitchen_spots: on

  - name: Eating
    entities:
      input_select.presence: Home
      input_select.scene: Eating
      automation.synchronise_scene_to_time_of_day: off
      automation.toggle_kitchen_spots_through_motion_sensor: off
      light.kitchen_worktop: off
      light.kitchen_spots: on