automation:
  - alias: Synchronise scene to time of day
    trigger:
      - platform: state
        entity_id: sensor.time_of_day
      - platform: state
        entity_id: group.everyone
        to: home
      - platform: state
        entity_id: climate.living_room
        to: Smart Schedule
    condition:
      - condition: state
        entity_id: group.everyone
        state: home
    action:
      - service: scene.turn_on
        data_template:
          entity_id: scene.{{ states('sensor.time_of_day') | lower | replace(' ', '_') }}

  - alias: Turn off Night scene
    trigger:
      - platform: time
        at: 06:30:00
      - platform: time
        at: 08:30:00
    condition:
      - condition: or
        conditions:
          - condition: time
            after: 06:30:00
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
          - condition: time
            after: 08:30:00
            weekday:
              - sat
              - sun
    action:
      - service: script.turn_on
        entity_id: script.scene_sync
      - condition: state
        entity_id: sensor.time_of_day
        state: Night
      - service: scene.turn_on
        data:
          entity_id: scene.morning

  - alias: Handle scene override
    trigger:
      - platform: state
        entity_id: input_select.presence
      - platform: state
        entity_id: input_select.scene
    action:
      - service: scene.turn_on
        data_template:
          entity_id: "scene.{{ trigger.to_state.state | lower | replace(' ', '_') }}"

script:
  scene_sync:
    alias: Sync scene to time of day
    sequence:
      - service: scene.turn_on
        data_template:
          entity_id: scene.{{ states('sensor.time_of_day') | lower | replace(' ', '_') }}
  scene_selection_reactivate:
    alias: Reactivate primary scene
    sequence:
      - service: scene.turn_on
        data_template:
          entity_id: scene.{{ states('input_select.scene') | lower | replace(' ', '_') }}

input_select:
  scene:
    icon: mdi:theme-light-dark
    name: Scene
    options:
      - Morning
      - Day
      - Afternoon
      - Early evening
      - Evening
      - Night
      - Away
      - Vacation

scene:
  - name: Home
    entities:
      input_select.presence: Home

  - name: Away
    entities:
      input_select.presence: Away
      input_select.scene: Away
      automation.synchronise_scene_to_time_of_day: on
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 16
      light.kitchen_mood_lighting: off
      light.kitchen_spots: off
      light.kitchen_worktop: off
      light.living_room_pendant: off
      light.toilet_spot: off
      remote.harmony_hub: off

  - name: Vacation
    entities:
      input_select.presence: Vacation
      input_select.scene: Vacation
      automation.synchronise_scene_to_time_of_day: on
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 16
      light.kitchen_mood_lighting: off
      light.kitchen_spots: off
      light.kitchen_worktop: off
      light.living_room_pendant: off
      light.toilet_spot: off
      remote.harmony_hub: off

  - name: Morning
    entities:
      input_select.presence: Home
      input_select.scene: Morning
      automation.synchronise_scene_to_time_of_day: on
      automation.toggle_kitchen_spots_through_motion_sensor: off
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 19
      light.kitchen_mood_lighting: off
      light.kitchen_spots: on
      light.kitchen_worktop: off
      light.living_room_pendant: on

  - name: Day
    entities:
      input_select.presence: Home
      input_select.scene: Day
      automation.synchronise_scene_to_time_of_day: on
      automation.toggle_kitchen_spots_through_motion_sensor: on
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 19
      light.kitchen_mood_lighting: off
      light.kitchen_worktop: off
      light.living_room_pendant: off

  - name: Afternoon
    entities:
      input_select.presence: Home
      input_select.scene: Afternoon
      automation.synchronise_scene_to_time_of_day: on
      automation.toggle_kitchen_spots_through_motion_sensor: on
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 19
      light.kitchen_mood_lighting: on
      light.kitchen_worktop: off
      light.living_room_pendant: on

  - name: Early evening
    entities:
      input_select.presence: Home
      input_select.scene: Early evening
      automation.synchronise_scene_to_time_of_day: on
      automation.toggle_kitchen_spots_through_motion_sensor: on
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 19
      light.kitchen_mood_lighting: on
      light.kitchen_worktop: off
      light.living_room_pendant: on

  - name: Evening
    entities:
      input_select.presence: Home
      input_select.scene: Evening
      automation.synchronise_scene_to_time_of_day: on
      automation.toggle_kitchen_spots_through_motion_sensor: on
      automation.turn_off_night_scene: off
      climate.living_room:
        state: heat
        temperature: 19
      light.kitchen_mood_lighting: on
      light.kitchen_worktop: off
      light.living_room_pendant: on

  - name: Night
    entities:
      input_select.presence: Home
      input_select.scene: Night
      automation.synchronise_scene_to_time_of_day: off
      automation.toggle_kitchen_spots_through_motion_sensor: on
      automation.turn_off_night_scene: on
      climate.living_room:
        state: heat
        temperature: 16
      light.kitchen_mood_lighting: off
      light.kitchen_spots: off
      light.kitchen_worktop: off
      light.living_room_pendant: off
      remote.harmony_hub: off

  - name: Cooking
    entities:
      automation.toggle_kitchen_spots_through_motion_sensor: off
      light.kitchen_worktop: on
      light.kitchen_spots: on
