input_select:
  presense:
    icon: mdi:home-circle
    name: Presence
    options:
      - Home
      - Away
      - Vacation
  primary_scene:
    icon: mdi:theme-light-dark
    name: Scene
    options:
      - Morning
      - Day
      - Afternoon
      - Dusk
      - Evening
      - Night
      - Away
      - Vacation
  secondary_scene:
    name: Activity
    options:
      - None
      - Cleaning
      - Cooking
      - Movie

automation:
  - alias: Handle scene selection
    trigger:
      - platform: state
        entity_id: input_select.presense
      - platform: state
        entity_id: input_select.primary_scene
      - platform: state
        entity_id: input_select.secondary_scene
    condition:
      condition: template
      value_template: "{{ trigger.to_state.state != 'None' }}"
    action:
      - service: scene.turn_on
        data_template:
          entity_id: "scene.{{ trigger.to_state.state }}"

  - alias: Re-activate primary scene upon secondary scene end
    trigger:
      - platform: state
        entity_id: input_select.secondary_scene
        to: None
    action:
      - service: scene.turn_on
        data_template:
          entity_id: "scene.{{ states('input_select.primary_scene') }}"

scene:
  - name: Home
    entities:
      input_select.presense:
        option: Home
      automation.set_home_mode_to_home: off
      automation.set_home_mode_to_away: on
      automation.set_home_mode_to_vacation: on
      automation.set_scene_to_morning: on
      automation.set_scene_to_day: on
      automation.set_scene_to_afternoon: on
      automation.set_scene_to_dusk: on
      automation.set_scene_to_evening: on
      automation.set_scene_to_night: on
      automation.turn_on_receiver_when_audio_starts_playing: on
      automation.turn_on_tv_when_media_starts_playing: on

  - name: Away
    entities:
      input_select.presense:
        option: Away
      input_select.primary_scene:
        option: Away
      input_select.secondary_scene:
        option: None
      automation.set_home_mode_to_home: on
      automation.set_home_mode_to_away: off
      automation.set_home_mode_to_vacation: on
      automation.set_scene_to_morning: on
      automation.set_scene_to_day: on
      automation.set_scene_to_afternoon: on
      automation.set_scene_to_dusk: on
      automation.set_scene_to_evening: on
      automation.set_scene_to_night: on
      automation.turn_on_receiver_when_audio_starts_playing: off
      automation.turn_on_tv_when_media_starts_playing: off
      climate.living_room:
        temperature: 16
      media_player.kitchen_speakers: off
      media_player.living_room_tv: off
      media_player.upstairs: off
      remote.harmony_hub: off

  - name: Vacation
    entities:
      input_select.presense:
        option: Vacation
      input_select.primary_scene:
        option: Vacation
      input_select.secondary_scene:
        option: None
      automation.set_home_mode_to_home: on
      automation.set_home_mode_to_away: off
      automation.set_home_mode_to_vacation: off
      automation.set_scene_to_morning: off
      automation.set_scene_to_day: off
      automation.set_scene_to_afternoon: off
      automation.set_scene_to_dusk: off
      automation.set_scene_to_evening: off
      automation.set_scene_to_night: off
      automation.turn_on_receiver_when_audio_starts_playing: off
      automation.turn_on_tv_when_media_starts_playing: off
      climate.living_room:
        temperature: 16
      media_player.kitchen_speakers: off
      media_player.living_room_tv: off
      media_player.upstairs: off
      remote.harmony_hub: off

  - name: Morning
    entities:
      input_select.presense:
        option: Home
      input_select.primary_scene:
        option: Morning
      automation.set_home_mode_to_home: off
      automation.set_home_mode_to_away: on
      automation.set_home_mode_to_vacation: on
      automation.set_scene_to_morning: off
      automation.set_scene_to_day: on
      automation.set_scene_to_afternoon: on
      automation.set_scene_to_dusk: on
      automation.set_scene_to_evening: on
      automation.set_scene_to_night: on
      climate.living_room:
        temperature: 19

  - name: Day
    entities:
      input_select.presense:
        option: Home
      input_select.primary_scene:
        option: Day
      automation.set_home_mode_to_home: off
      automation.set_home_mode_to_away: on
      automation.set_home_mode_to_vacation: on
      automation.set_scene_to_morning: off
      automation.set_scene_to_day: off
      automation.set_scene_to_afternoon: on
      automation.set_scene_to_dusk: on
      automation.set_scene_to_evening: on
      automation.set_scene_to_night: on
      climate.living_room:
        temperature: 19

  - name: Afternoon
    entities:
      input_select.presense:
        option: Home
      input_select.primary_scene:
        option: Afternoon
      automation.set_home_mode_to_home: off
      automation.set_home_mode_to_away: on
      automation.set_home_mode_to_vacation: on
      automation.set_scene_to_morning: off
      automation.set_scene_to_day: off
      automation.set_scene_to_afternoon: off
      automation.set_scene_to_dusk: on
      automation.set_scene_to_evening: on
      automation.set_scene_to_night: on
      climate.living_room:
        temperature: 20

  - name: Dusk
    entities:
      input_select.presense:
        option: Home
      input_select.primary_scene:
        option: Dusk
      automation.set_home_mode_to_home: off
      automation.set_home_mode_to_away: on
      automation.set_home_mode_to_vacation: on
      automation.set_scene_to_morning: off
      automation.set_scene_to_day: off
      automation.set_scene_to_afternoon: off
      automation.set_scene_to_dusk: off
      automation.set_scene_to_evening: on
      automation.set_scene_to_night: on
      climate.living_room:
        temperature: 20

  - name: Evening
    entities:
      input_select.presense:
        option: Home
      input_select.primary_scene:
        option: Evening
      automation.set_home_mode_to_home: off
      automation.set_home_mode_to_away: on
      automation.set_home_mode_to_vacation: on
      automation.set_scene_to_morning: off
      automation.set_scene_to_day: off
      automation.set_scene_to_afternoon: off
      automation.set_scene_to_dusk: off
      automation.set_scene_to_evening: off
      automation.set_scene_to_night: on
      climate.living_room:
        temperature: 20

  - name: Night
    entities:
      input_select.presense:
        option: Home
      input_select.primary_scene:
        option: Night
      automation.set_home_mode_to_home: off
      automation.set_home_mode_to_away: on
      automation.set_home_mode_to_vacation: on
      automation.set_scene_to_morning: on
      automation.set_scene_to_day: off
      automation.set_scene_to_afternoon: off
      automation.set_scene_to_dusk: off
      automation.set_scene_to_evening: off
      automation.set_scene_to_night: off
      climate.living_room:
        temperature: 16
      media_player.kitchen_speakers: off
      media_player.living_room_tv: off
      media_player.upstairs: off

  - name: Cleaning
    entities:
      input_select.presense:
        option: Home
      input_select.secondary_scene:
        option: Cleaning

  - name: Cooking
    entities:
      input_select.presense:
        option: Home
      input_select.secondary_scene:
        option: Cooking

  - name: Movie
    entities:
      input_select.presense:
        option: Home
      input_select.secondary_scene:
        option: Movie
