automation:
  - alias: Notify when the front door opens while no one is home
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition:
      - condition: state
        entity_id: sensor.current_scene
        state: Away
    action:
      - service: notify.all_devices
        data:
          title: "Possible intrusion detected"
          message: "The front door just opened while no one is home"
          data:
            channel: Intrusion detection
            importance: max

  - alias: Notify when the kitchen door opens while no one is home
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_door
        to: "on"
    condition:
      - condition: state
        entity_id: sensor.current_scene
        state: Away
    action:
      - service: notify.all_devices
        data:
          title: "Possible intrusion detected"
          message: "The kitchen door just opened while no one is home"
          data:
            channel: Intrusion detection
            importance: max

  - alias: Notify when the living room window opens while no one is home
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_window
        to: "on"
    condition:
      - condition: state
        entity_id: sensor.current_scene
        state: Away
    action:
      - service: notify.all_devices
        data:
          title: "Possible intrusion detected"
          message: "The living room window just opened while no one is home"
          data:
            channel: Intrusion detection
            importance: max
