automation:
  - alias: Set theme at startup
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data:
        name: light

script:
  reload_themes:
    alias: Reload themes
    sequence:
      - service: frontend.reload_themes
