automation:
  - alias: Set theme
    description: Set the correct themes when Home Assistant starts
    trigger:
      # Trigger immediately when Home Assistant starts
      - platform: homeassistant
        event: start
    action:
      - service: script.set_theme

binary_sensor:
  - platform: tod
    name: Cooking time
    after: "17:30"
    before: "19:30"
  - platform: tod
    name: Bedtime
    after: "21:30"
    before: "06:30"
  # TODO: Add sensor to suggest keeping on the lights in the kitchen (when they're frequently turned on in a period for example)

frontend:
  themes: !include_dir_named ../themes/

lovelace:
  dashboards:
    ui-insights:
      filename: ui-insights.yaml
      icon: mdi:google-assistant
      mode: yaml
      title: Insights
    ui-settings:
      filename: ui-settings.yaml
      icon: mdi:cog-outline
      mode: yaml
      title: Settings
      require_admin: true
  mode: yaml
  resources:
    - url: https://fonts.googleapis.com/css?family=Product+Sans:300,400,500
      type: css
    - url: /local/js/auto-entities.js?v=21.11.2020
      type: module
    - url: /local/js/card-mod.js?v=11.10.2020
      type: module
    - url: /local/js/fold-entity-row.js?v=4.7.2020
      type: module
    - url: /local/js/layout-card.js?v=30.6.2020
      type: module
    - url: /local/js/layout-card-griddier.js
      type: module
    - url: /local/js/mini-media-player.js
      type: module
    - url: /local/js/paper-buttons-row.js?v=0.3.0
      type: module
    - url: /local/js/simple-weather-card.js?v=0.8.1
      type: module
    - url: /local/js/template-entity-row.js
      type: module

script:
  reload_themes:
    alias: Reload themes
    sequence:
      - service: frontend.reload_themes
  set_theme:
    alias: Set theme
    sequence:
      - service: frontend.set_theme
        data:
          mode: light
          name: soft-light
      - service: frontend.set_theme
        data:
          mode: dark
          name: soft-dark

sensor:
  - platform: average
    entities:
      - climate.bathroom
      - climate.bedroom
      - climate.office
    name: Downstairs temperature
    precision: 1
  - platform: average
    entities:
      - climate.living_room
      - climate.kitchen
    name: Upstairs temperature
    precision: 1
