automation:
  - alias: Toggle work mode
    trigger:
      # Niels' MacBook Pro
      - platform: state
        entity_id: device_tracker.niels_macbook_pro
      - platform: state
        entity_id: binary_sensor.niels_macbook_pro_active
      - platform: state
        entity_id: sensor.niels_macbook_pro_primary_display_name
      # Laura's Lenovo IdeaPad
      # TODO
    action:
      - alias: Turn on Work mode if conditions are met, else turn it off
        choose:
          # IF Niels' MacBook Pro is connected
          - alias: Niels' MacBook Pro is connected
            conditions:
              - condition: state
                entity_id: device_tracker.niels_macbook_pro
                state: home
              - condition: state
                entity_id: binary_sensor.niels_macbook_pro_active
                state: "on"
              - condition: state
                entity_id: sensor.niels_macbook_pro_primary_display_name
                state: LG HDR 4K
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.work_mode
          # ELSE IF Laura's IdeaPad is connected
          # - alias: Laura's IdeaPad is connected
          #   conditions:
          #     -
          #   sequence:
          #     - service: input_boolean.turn_on
          #       entity_id: input_boolean.work_mode
        default:
          # ELSE
          - service: input_boolean.turn_off
            entity_id: input_boolean.work_mode

input_boolean:
  work_mode:
    icon: mdi:briefcase-outline
    name: Work mode
