automation:
  - alias: Handle pairing mode change
    trigger:
      - platform: state
        entity_id: input_boolean.zigbee_permit_join
    action:
      - service: mqtt.publish
        data_template:
          topic: zigbee2mqtt/bridge/config/permit_join
          payload: >-
            {% if trigger.to_state.state == "on" %}
              true
            {% else %}
              false
            {% endif %}

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

mqtt:
  broker: localhost
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
