automation:
  - alias: Handle pairing mode change
    trigger:
      - platform: state
        entity_id: input_boolean.zigbee_permit_join
      - platform: mqtt
        topic: zigbee2mqtt/bridge/state
        payload: offline
    action:
      - service: mqtt.publish
        data_template:
          topic: zigbee2mqtt/bridge/config/permit_join
          payload: >-
            {% if trigger.to_state.state == "on" %}
              true
            {% else %}
              false
            {% endif %}

  - alias: Generate network map every hour
    trigger:
      - platform: time_pattern
        minutes: 0
        seconds: 0
    action:
      - service: script.turn_on
        entity_id: script.generate_network_map

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

mqtt:
  broker: localhost
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

script:
  generate_network_map:
    alias: Generate Zigbee network map
    sequence:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/bridge/networkmap
          payload: graphviz
